/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

module bridge(clk, arvalid, res_n, arburst, arlen, araddr, arready, rdata, rresp, rlast, rready, rvalid, awvalid, awaddr, awready, awlen, awburst, wvalid, wdata, wready, wlast
, bready, bvalid, bresp, PADDR, PWDATA, PRDATA, PWRITE, PENABLE, PSEL1, PSEL2, PSEL3, PSEL4, PREADY);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire \DADDR[0] ;
  wire \DADDR[1] ;
  wire \DADDR[2] ;
  wire DWREQ;
  output [2:0] PADDR;
  wire [2:0] PADDR;
  output PENABLE;
  wire PENABLE;
  input [15:0] PRDATA;
  wire [15:0] PRDATA;
  input PREADY;
  wire PREADY;
  output PSEL1;
  wire PSEL1;
  output PSEL2;
  wire PSEL2;
  output PSEL3;
  wire PSEL3;
  output PSEL4;
  wire PSEL4;
  output [15:0] PWDATA;
  wire [15:0] PWDATA;
  output PWRITE;
  wire PWRITE;
  input [4:0] araddr;
  wire [4:0] araddr;
  wire \araddr_pipe[0] ;
  wire \araddr_pipe[1] ;
  wire \araddr_pipe[2] ;
  input [1:0] arburst;
  wire [1:0] arburst;
  wire \arburst_pipe[0] ;
  wire \arburst_pipe[1] ;
  input [3:0] arlen;
  wire [3:0] arlen;
  wire \arlen_pipe[0] ;
  wire \arlen_pipe[1] ;
  wire \arlen_pipe[2] ;
  wire \arlen_pipe[3] ;
  output arready;
  wire arready;
  input arvalid;
  wire arvalid;
  wire arvalid_pipe;
  input [4:0] awaddr;
  wire [4:0] awaddr;
  wire \awaddr_pipe[0] ;
  wire \awaddr_pipe[1] ;
  wire \awaddr_pipe[2] ;
  input [1:0] awburst;
  wire [1:0] awburst;
  wire \awburst_pipe[0] ;
  wire \awburst_pipe[1] ;
  input [3:0] awlen;
  wire [3:0] awlen;
  wire \awlen_pipe[0] ;
  wire \awlen_pipe[1] ;
  wire \awlen_pipe[2] ;
  wire \awlen_pipe[3] ;
  output awready;
  wire awready;
  input awvalid;
  wire awvalid;
  wire awvalid_pipe;
  input bready;
  wire bready;
  output bresp;
  wire bresp;
  wire \burst[0] ;
  wire \burst[1] ;
  output bvalid;
  wire bvalid;
  input clk;
  wire clk;
  wire \current_state[0] ;
  wire \current_state[1] ;
  wire \current_state[2] ;
  wire \current_state[3] ;
  wire last;
  wire \lenM[0] ;
  wire \lenM[1] ;
  wire \lenM[2] ;
  wire \lenM[3] ;
  wire \lenS[0] ;
  wire \lenS[1] ;
  wire \lenS[2] ;
  wire \lenS[3] ;
  output [15:0] rdata;
  wire [15:0] rdata;
  input res_n;
  wire res_n;
  output rlast;
  wire rlast;
  input rready;
  wire rready;
  output rresp;
  wire rresp;
  output rvalid;
  wire rvalid;
  input [15:0] wdata;
  wire [15:0] wdata;
  input wlast;
  wire wlast;
  output wready;
  wire wready;
  input wvalid;
  wire wvalid;
  wire wvalid_pipe;
  sky130_fd_sc_hd__inv_2 _126_ (
    .A(\current_state[3] ),
    .Y(_107_)
  );
  sky130_fd_sc_hd__inv_2 _127_ (
    .A(\current_state[2] ),
    .Y(_108_)
  );
  sky130_fd_sc_hd__inv_2 _128_ (
    .A(arvalid_pipe),
    .Y(_109_)
  );
  sky130_fd_sc_hd__inv_2 _129_ (
    .A(\burst[0] ),
    .Y(_110_)
  );
  sky130_fd_sc_hd__inv_2 _130_ (
    .A(\lenM[3] ),
    .Y(_111_)
  );
  sky130_fd_sc_hd__inv_2 _131_ (
    .A(last),
    .Y(_112_)
  );
  sky130_fd_sc_hd__inv_2 _132_ (
    .A(wvalid_pipe),
    .Y(_113_)
  );
  sky130_fd_sc_hd__inv_2 _133_ (
    .A(\awlen_pipe[0] ),
    .Y(_114_)
  );
  sky130_fd_sc_hd__inv_2 _134_ (
    .A(\arlen_pipe[0] ),
    .Y(_115_)
  );
  sky130_fd_sc_hd__inv_2 _135_ (
    .A(\arlen_pipe[3] ),
    .Y(_116_)
  );
  sky130_fd_sc_hd__and2_2 _136_ (
    .A(\current_state[1] ),
    .B(\current_state[0] ),
    .X(_117_)
  );
  sky130_fd_sc_hd__and2b_2 _137_ (
    .A_N(\current_state[2] ),
    .B(\current_state[3] ),
    .X(_118_)
  );
  sky130_fd_sc_hd__and3b_2 _138_ (
    .A_N(\current_state[2] ),
    .B(\current_state[0] ),
    .C(\current_state[1] ),
    .X(_119_)
  );
  sky130_fd_sc_hd__nand3b_2 _139_ (
    .A_N(\current_state[2] ),
    .B(\current_state[0] ),
    .C(\current_state[1] ),
    .Y(_120_)
  );
  sky130_fd_sc_hd__nor2_2 _140_ (
    .A(_107_),
    .B(_120_),
    .Y(PWRITE)
  );
  sky130_fd_sc_hd__and2b_2 _141_ (
    .A_N(\current_state[3] ),
    .B(\current_state[2] ),
    .X(_121_)
  );
  sky130_fd_sc_hd__or4bb_2 _142_ (
    .A(\current_state[0] ),
    .B(\current_state[3] ),
    .C_N(\current_state[2] ),
    .D_N(\current_state[1] ),
    .X(_122_)
  );
  sky130_fd_sc_hd__inv_2 _143_ (
    .A(_122_),
    .Y(awready)
  );
  sky130_fd_sc_hd__and4bb_2 _144_ (
    .A_N(\current_state[1] ),
    .B_N(\current_state[3] ),
    .C(\current_state[2] ),
    .D(\current_state[0] ),
    .X(rresp)
  );
  sky130_fd_sc_hd__nor2_2 _145_ (
    .A(\current_state[1] ),
    .B(\current_state[0] ),
    .Y(_123_)
  );
  sky130_fd_sc_hd__nor4b_2 _146_ (
    .A(\current_state[1] ),
    .B(\current_state[0] ),
    .C(\current_state[2] ),
    .D_N(\current_state[3] ),
    .Y(wready)
  );
  sky130_fd_sc_hd__or4b_2 _147_ (
    .A(\current_state[1] ),
    .B(\current_state[3] ),
    .C(\current_state[2] ),
    .D_N(\current_state[0] ),
    .X(_124_)
  );
  sky130_fd_sc_hd__inv_2 _148_ (
    .A(_124_),
    .Y(arready)
  );
  sky130_fd_sc_hd__and4bb_2 _149_ (
    .A_N(\current_state[1] ),
    .B_N(\current_state[2] ),
    .C(\current_state[3] ),
    .D(\current_state[0] ),
    .X(bresp)
  );
  sky130_fd_sc_hd__or3b_2 _150_ (
    .A(\current_state[0] ),
    .B(\current_state[2] ),
    .C_N(\current_state[1] ),
    .X(_125_)
  );
  sky130_fd_sc_hd__nor2_2 _151_ (
    .A(\current_state[3] ),
    .B(_125_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__or2_2 _152_ (
    .A(_119_),
    .B(_019_),
    .X(PENABLE)
  );
  sky130_fd_sc_hd__and2_2 _153_ (
    .A(last),
    .B(rresp),
    .X(rlast)
  );
  sky130_fd_sc_hd__and2_2 _154_ (
    .A(DWREQ),
    .B(\DADDR[0] ),
    .X(PADDR[0])
  );
  sky130_fd_sc_hd__and2_2 _155_ (
    .A(DWREQ),
    .B(\DADDR[1] ),
    .X(PADDR[1])
  );
  sky130_fd_sc_hd__and2_2 _156_ (
    .A(DWREQ),
    .B(\DADDR[2] ),
    .X(PADDR[2])
  );
  sky130_fd_sc_hd__a2bb2o_2 _157_ (
    .A1_N(awvalid_pipe),
    .A2_N(_122_),
    .B1(arready),
    .B2(_109_),
    .X(_020_)
  );
  sky130_fd_sc_hd__a21o_2 _158_ (
    .A1(_122_),
    .A2(_124_),
    .B1(_020_),
    .X(_021_)
  );
  sky130_fd_sc_hd__mux2_1 _159_ (
    .A0(\arburst_pipe[0] ),
    .A1(\awburst_pipe[0] ),
    .S(_124_),
    .X(_022_)
  );
  sky130_fd_sc_hd__mux2_1 _160_ (
    .A0(_022_),
    .A1(\burst[0] ),
    .S(_021_),
    .X(_000_)
  );
  sky130_fd_sc_hd__mux2_1 _161_ (
    .A0(\arburst_pipe[1] ),
    .A1(\awburst_pipe[1] ),
    .S(_124_),
    .X(_023_)
  );
  sky130_fd_sc_hd__mux2_1 _162_ (
    .A0(_023_),
    .A1(\burst[1] ),
    .S(_021_),
    .X(_001_)
  );
  sky130_fd_sc_hd__nor2_2 _163_ (
    .A(\lenS[0] ),
    .B(\lenS[1] ),
    .Y(_024_)
  );
  sky130_fd_sc_hd__or3_2 _164_ (
    .A(\lenS[0] ),
    .B(\lenS[1] ),
    .C(\lenS[2] ),
    .X(_025_)
  );
  sky130_fd_sc_hd__nor4_2 _165_ (
    .A(\lenS[0] ),
    .B(\lenS[1] ),
    .C(\lenS[2] ),
    .D(\lenS[3] ),
    .Y(_026_)
  );
  sky130_fd_sc_hd__or4_2 _166_ (
    .A(\lenS[0] ),
    .B(\lenS[1] ),
    .C(\lenS[2] ),
    .D(\lenS[3] ),
    .X(_027_)
  );
  sky130_fd_sc_hd__o211a_2 _167_ (
    .A1(_120_),
    .A2(_026_),
    .B1(_124_),
    .C1(_122_),
    .X(_028_)
  );
  sky130_fd_sc_hd__and3b_2 _168_ (
    .A_N(PREADY),
    .B(_119_),
    .C(\current_state[3] ),
    .X(_029_)
  );
  sky130_fd_sc_hd__nor3_2 _169_ (
    .A(_020_),
    .B(_028_),
    .C(_029_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__nor2_2 _170_ (
    .A(_119_),
    .B(arready),
    .Y(_031_)
  );
  sky130_fd_sc_hd__a2bb2o_2 _171_ (
    .A1_N(\lenS[0] ),
    .A2_N(_120_),
    .B1(arready),
    .B2(\arlen_pipe[0] ),
    .X(_032_)
  );
  sky130_fd_sc_hd__a21o_2 _172_ (
    .A1(_114_),
    .A2(_031_),
    .B1(_032_),
    .X(_033_)
  );
  sky130_fd_sc_hd__mux2_1 _173_ (
    .A0(\lenS[0] ),
    .A1(_033_),
    .S(_030_),
    .X(_002_)
  );
  sky130_fd_sc_hd__a2111o_2 _174_ (
    .A1(\lenS[0] ),
    .A2(_119_),
    .B1(_020_),
    .C1(_028_),
    .D1(_029_),
    .X(_034_)
  );
  sky130_fd_sc_hd__and2_2 _175_ (
    .A(\arlen_pipe[1] ),
    .B(arready),
    .X(_035_)
  );
  sky130_fd_sc_hd__xor2_2 _176_ (
    .A(\awlen_pipe[0] ),
    .B(\awlen_pipe[1] ),
    .X(_036_)
  );
  sky130_fd_sc_hd__a221o_2 _177_ (
    .A1(_119_),
    .A2(_024_),
    .B1(_031_),
    .B2(_036_),
    .C1(_035_),
    .X(_037_)
  );
  sky130_fd_sc_hd__a22o_2 _178_ (
    .A1(\lenS[1] ),
    .A2(_034_),
    .B1(_037_),
    .B2(_030_),
    .X(_003_)
  );
  sky130_fd_sc_hd__a21oi_2 _179_ (
    .A1(\awlen_pipe[0] ),
    .A2(\awlen_pipe[1] ),
    .B1(\awlen_pipe[2] ),
    .Y(_038_)
  );
  sky130_fd_sc_hd__and3_2 _180_ (
    .A(\awlen_pipe[0] ),
    .B(\awlen_pipe[1] ),
    .C(\awlen_pipe[2] ),
    .X(_039_)
  );
  sky130_fd_sc_hd__nor2_2 _181_ (
    .A(_038_),
    .B(_039_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__o21ai_2 _182_ (
    .A1(\lenS[0] ),
    .A2(\lenS[1] ),
    .B1(\lenS[2] ),
    .Y(_041_)
  );
  sky130_fd_sc_hd__a21oi_2 _183_ (
    .A1(_025_),
    .A2(_041_),
    .B1(_120_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__a221o_2 _184_ (
    .A1(\arlen_pipe[2] ),
    .A2(arready),
    .B1(_031_),
    .B2(_040_),
    .C1(_042_),
    .X(_043_)
  );
  sky130_fd_sc_hd__mux2_1 _185_ (
    .A0(\lenS[2] ),
    .A1(_043_),
    .S(_030_),
    .X(_004_)
  );
  sky130_fd_sc_hd__xor2_2 _186_ (
    .A(\awlen_pipe[3] ),
    .B(_039_),
    .X(_044_)
  );
  sky130_fd_sc_hd__o31a_2 _187_ (
    .A1(\lenS[0] ),
    .A2(\lenS[1] ),
    .A3(\lenS[2] ),
    .B1(\lenS[3] ),
    .X(_045_)
  );
  sky130_fd_sc_hd__o21a_2 _188_ (
    .A1(_026_),
    .A2(_045_),
    .B1(_119_),
    .X(_046_)
  );
  sky130_fd_sc_hd__a221o_2 _189_ (
    .A1(\arlen_pipe[3] ),
    .A2(arready),
    .B1(_031_),
    .B2(_044_),
    .C1(_046_),
    .X(_047_)
  );
  sky130_fd_sc_hd__mux2_1 _190_ (
    .A0(\lenS[3] ),
    .A1(_047_),
    .S(_030_),
    .X(_005_)
  );
  sky130_fd_sc_hd__and3_2 _191_ (
    .A(_107_),
    .B(_108_),
    .C(_123_),
    .X(_048_)
  );
  sky130_fd_sc_hd__nand2_2 _192_ (
    .A(_109_),
    .B(_048_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__and2_2 _193_ (
    .A(bready),
    .B(bresp),
    .X(_050_)
  );
  sky130_fd_sc_hd__o31a_2 _194_ (
    .A1(DWREQ),
    .A2(_048_),
    .A3(_050_),
    .B1(_049_),
    .X(_006_)
  );
  sky130_fd_sc_hd__nor3_2 _195_ (
    .A(\lenM[1] ),
    .B(\lenM[2] ),
    .C(\lenM[3] ),
    .Y(_051_)
  );
  sky130_fd_sc_hd__o211a_2 _196_ (
    .A1(\lenM[0] ),
    .A2(_048_),
    .B1(_051_),
    .C1(rresp),
    .X(_052_)
  );
  sky130_fd_sc_hd__o21bai_2 _197_ (
    .A1(_112_),
    .A2(_048_),
    .B1_N(_052_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__nor3_2 _198_ (
    .A(rresp),
    .B(wready),
    .C(arready),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nor4_2 _199_ (
    .A(awready),
    .B(rresp),
    .C(wready),
    .D(arready),
    .Y(_054_)
  );
  sky130_fd_sc_hd__or4_2 _200_ (
    .A(\lenM[0] ),
    .B(\lenM[1] ),
    .C(\lenM[2] ),
    .D(\lenM[3] ),
    .X(_055_)
  );
  sky130_fd_sc_hd__o21ba_2 _201_ (
    .A1(rresp),
    .A2(wready),
    .B1_N(\lenM[0] ),
    .X(_056_)
  );
  sky130_fd_sc_hd__o21ba_2 _202_ (
    .A1(rresp),
    .A2(wready),
    .B1_N(_055_),
    .X(_057_)
  );
  sky130_fd_sc_hd__or3_2 _203_ (
    .A(_020_),
    .B(_054_),
    .C(_057_),
    .X(_058_)
  );
  sky130_fd_sc_hd__a221o_2 _204_ (
    .A1(_115_),
    .A2(arready),
    .B1(_053_),
    .B2(_114_),
    .C1(_056_),
    .X(_059_)
  );
  sky130_fd_sc_hd__mux2_1 _205_ (
    .A0(_059_),
    .A1(\lenM[0] ),
    .S(_058_),
    .X(_008_)
  );
  sky130_fd_sc_hd__or2_2 _206_ (
    .A(\arlen_pipe[0] ),
    .B(\arlen_pipe[1] ),
    .X(_060_)
  );
  sky130_fd_sc_hd__nand2_2 _207_ (
    .A(\arlen_pipe[0] ),
    .B(\arlen_pipe[1] ),
    .Y(_061_)
  );
  sky130_fd_sc_hd__and3_2 _208_ (
    .A(arready),
    .B(_060_),
    .C(_061_),
    .X(_062_)
  );
  sky130_fd_sc_hd__nor2_2 _209_ (
    .A(\lenM[0] ),
    .B(\lenM[1] ),
    .Y(_063_)
  );
  sky130_fd_sc_hd__and2_2 _210_ (
    .A(\lenM[0] ),
    .B(\lenM[1] ),
    .X(_064_)
  );
  sky130_fd_sc_hd__o22a_2 _211_ (
    .A1(rresp),
    .A2(wready),
    .B1(_063_),
    .B2(_064_),
    .X(_065_)
  );
  sky130_fd_sc_hd__a211o_2 _212_ (
    .A1(_036_),
    .A2(_053_),
    .B1(_062_),
    .C1(_065_),
    .X(_066_)
  );
  sky130_fd_sc_hd__mux2_1 _213_ (
    .A0(_066_),
    .A1(\lenM[1] ),
    .S(_058_),
    .X(_009_)
  );
  sky130_fd_sc_hd__nand3_2 _214_ (
    .A(\arlen_pipe[0] ),
    .B(\arlen_pipe[1] ),
    .C(\arlen_pipe[2] ),
    .Y(_067_)
  );
  sky130_fd_sc_hd__a21o_2 _215_ (
    .A1(\arlen_pipe[0] ),
    .A2(\arlen_pipe[1] ),
    .B1(\arlen_pipe[2] ),
    .X(_068_)
  );
  sky130_fd_sc_hd__and3_2 _216_ (
    .A(arready),
    .B(_067_),
    .C(_068_),
    .X(_069_)
  );
  sky130_fd_sc_hd__or3_2 _217_ (
    .A(\lenM[0] ),
    .B(\lenM[1] ),
    .C(\lenM[2] ),
    .X(_070_)
  );
  sky130_fd_sc_hd__o21ai_2 _218_ (
    .A1(\lenM[0] ),
    .A2(\lenM[1] ),
    .B1(\lenM[2] ),
    .Y(_071_)
  );
  sky130_fd_sc_hd__a2bb2oi_2 _219_ (
    .A1_N(rresp),
    .A2_N(wready),
    .B1(_070_),
    .B2(_071_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__a211o_2 _220_ (
    .A1(_040_),
    .A2(_053_),
    .B1(_069_),
    .C1(_072_),
    .X(_073_)
  );
  sky130_fd_sc_hd__mux2_1 _221_ (
    .A0(_073_),
    .A1(\lenM[2] ),
    .S(_058_),
    .X(_010_)
  );
  sky130_fd_sc_hd__nand2_2 _222_ (
    .A(_116_),
    .B(_067_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__or2_2 _223_ (
    .A(_116_),
    .B(_067_),
    .X(_075_)
  );
  sky130_fd_sc_hd__o211a_2 _224_ (
    .A1(rresp),
    .A2(wready),
    .B1(_070_),
    .C1(\lenM[3] ),
    .X(_076_)
  );
  sky130_fd_sc_hd__a311o_2 _225_ (
    .A1(arready),
    .A2(_074_),
    .A3(_075_),
    .B1(_076_),
    .C1(_057_),
    .X(_077_)
  );
  sky130_fd_sc_hd__a2111o_2 _226_ (
    .A1(_044_),
    .A2(_053_),
    .B1(_054_),
    .C1(_057_),
    .D1(_020_),
    .X(_078_)
  );
  sky130_fd_sc_hd__o2bb2a_2 _227_ (
    .A1_N(_111_),
    .A2_N(_058_),
    .B1(_077_),
    .B2(_078_),
    .X(_011_)
  );
  sky130_fd_sc_hd__o2111a_2 _228_ (
    .A1(\burst[1] ),
    .A2(_110_),
    .B1(_119_),
    .C1(_027_),
    .D1(_107_),
    .X(_079_)
  );
  sky130_fd_sc_hd__or4_2 _229_ (
    .A(_020_),
    .B(_028_),
    .C(_029_),
    .D(_079_),
    .X(_080_)
  );
  sky130_fd_sc_hd__nor2_2 _230_ (
    .A(\DADDR[0] ),
    .B(_120_),
    .Y(_081_)
  );
  sky130_fd_sc_hd__a221o_2 _231_ (
    .A1(\araddr_pipe[0] ),
    .A2(arready),
    .B1(_031_),
    .B2(\awaddr_pipe[0] ),
    .C1(_081_),
    .X(_082_)
  );
  sky130_fd_sc_hd__mux2_1 _232_ (
    .A0(_082_),
    .A1(\DADDR[0] ),
    .S(_080_),
    .X(_012_)
  );
  sky130_fd_sc_hd__nand2_2 _233_ (
    .A(\DADDR[0] ),
    .B(\DADDR[1] ),
    .Y(_083_)
  );
  sky130_fd_sc_hd__or2_2 _234_ (
    .A(\DADDR[0] ),
    .B(\DADDR[1] ),
    .X(_084_)
  );
  sky130_fd_sc_hd__and3_2 _235_ (
    .A(_119_),
    .B(_083_),
    .C(_084_),
    .X(_085_)
  );
  sky130_fd_sc_hd__a221o_2 _236_ (
    .A1(\araddr_pipe[1] ),
    .A2(arready),
    .B1(_031_),
    .B2(\awaddr_pipe[1] ),
    .C1(_085_),
    .X(_086_)
  );
  sky130_fd_sc_hd__mux2_1 _237_ (
    .A0(_086_),
    .A1(\DADDR[1] ),
    .S(_080_),
    .X(_013_)
  );
  sky130_fd_sc_hd__a21o_2 _238_ (
    .A1(\DADDR[0] ),
    .A2(\DADDR[1] ),
    .B1(\DADDR[2] ),
    .X(_087_)
  );
  sky130_fd_sc_hd__nand3_2 _239_ (
    .A(\DADDR[0] ),
    .B(\DADDR[1] ),
    .C(\DADDR[2] ),
    .Y(_088_)
  );
  sky130_fd_sc_hd__and3_2 _240_ (
    .A(_119_),
    .B(_087_),
    .C(_088_),
    .X(_089_)
  );
  sky130_fd_sc_hd__a221o_2 _241_ (
    .A1(\araddr_pipe[2] ),
    .A2(arready),
    .B1(_031_),
    .B2(\awaddr_pipe[2] ),
    .C1(_089_),
    .X(_090_)
  );
  sky130_fd_sc_hd__mux2_1 _242_ (
    .A0(_090_),
    .A1(\DADDR[2] ),
    .S(_080_),
    .X(_014_)
  );
  sky130_fd_sc_hd__a21o_2 _243_ (
    .A1(PWRITE),
    .A2(_026_),
    .B1(_019_),
    .X(_091_)
  );
  sky130_fd_sc_hd__o21ai_2 _244_ (
    .A1(\current_state[1] ),
    .A2(bready),
    .B1(\current_state[0] ),
    .Y(_092_)
  );
  sky130_fd_sc_hd__a32o_2 _245_ (
    .A1(rready),
    .A2(_121_),
    .A3(_123_),
    .B1(_092_),
    .B2(_118_),
    .X(_093_)
  );
  sky130_fd_sc_hd__a32o_2 _246_ (
    .A1(_113_),
    .A2(_117_),
    .A3(_121_),
    .B1(awready),
    .B2(awvalid_pipe),
    .X(_094_)
  );
  sky130_fd_sc_hd__a211o_2 _247_ (
    .A1(arvalid_pipe),
    .A2(_048_),
    .B1(_093_),
    .C1(_094_),
    .X(_095_)
  );
  sky130_fd_sc_hd__a21o_2 _248_ (
    .A1(PREADY),
    .A2(_091_),
    .B1(_095_),
    .X(_015_)
  );
  sky130_fd_sc_hd__nand2b_2 _249_ (
    .A_N(wlast),
    .B(_055_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__and3b_2 _250_ (
    .A_N(wlast),
    .B(wready),
    .C(_055_),
    .X(_097_)
  );
  sky130_fd_sc_hd__a311o_2 _251_ (
    .A1(_109_),
    .A2(awvalid_pipe),
    .A3(_048_),
    .B1(_094_),
    .C1(_097_),
    .X(_098_)
  );
  sky130_fd_sc_hd__a21o_2 _252_ (
    .A1(arvalid_pipe),
    .A2(arready),
    .B1(_050_),
    .X(_099_)
  );
  sky130_fd_sc_hd__or4b_2 _253_ (
    .A(\lenS[1] ),
    .B(\lenS[2] ),
    .C(\lenS[3] ),
    .D_N(\lenS[0] ),
    .X(_100_)
  );
  sky130_fd_sc_hd__and4_2 _254_ (
    .A(\current_state[3] ),
    .B(PREADY),
    .C(_119_),
    .D(_100_),
    .X(_101_)
  );
  sky130_fd_sc_hd__a31o_2 _255_ (
    .A1(_107_),
    .A2(_119_),
    .A3(_027_),
    .B1(_101_),
    .X(_102_)
  );
  sky130_fd_sc_hd__or4b_2 _256_ (
    .A(_098_),
    .B(_099_),
    .C(_102_),
    .D_N(_125_),
    .X(_016_)
  );
  sky130_fd_sc_hd__a2111o_2 _257_ (
    .A1(\current_state[0] ),
    .A2(_051_),
    .B1(\current_state[3] ),
    .C1(\current_state[1] ),
    .D1(_108_),
    .X(_103_)
  );
  sky130_fd_sc_hd__o31ai_2 _258_ (
    .A1(\current_state[3] ),
    .A2(_120_),
    .A3(_027_),
    .B1(_103_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__or2_2 _259_ (
    .A(_098_),
    .B(_104_),
    .X(_017_)
  );
  sky130_fd_sc_hd__nor3b_2 _260_ (
    .A(_117_),
    .B(_123_),
    .C_N(_118_),
    .Y(_105_)
  );
  sky130_fd_sc_hd__a31o_2 _261_ (
    .A1(wvalid_pipe),
    .A2(_117_),
    .A3(_121_),
    .B1(_105_),
    .X(_106_)
  );
  sky130_fd_sc_hd__a211o_2 _262_ (
    .A1(wready),
    .A2(_096_),
    .B1(_101_),
    .C1(_106_),
    .X(_018_)
  );
  sky130_fd_sc_hd__dfrtp_2 _263_ (
    .CLK(clk),
    .D(_000_),
    .Q(\burst[0] ),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _264_ (
    .CLK(clk),
    .D(_001_),
    .Q(\burst[1] ),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _265_ (
    .CLK(clk),
    .D(_002_),
    .Q(\lenS[0] ),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _266_ (
    .CLK(clk),
    .D(_003_),
    .Q(\lenS[1] ),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _267_ (
    .CLK(clk),
    .D(_004_),
    .Q(\lenS[2] ),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _268_ (
    .CLK(clk),
    .D(_005_),
    .Q(\lenS[3] ),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _269_ (
    .CLK(clk),
    .D(_006_),
    .Q(DWREQ),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _270_ (
    .CLK(clk),
    .D(_007_),
    .Q(last),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _271_ (
    .CLK(clk),
    .D(_008_),
    .Q(\lenM[0] ),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _272_ (
    .CLK(clk),
    .D(_009_),
    .Q(\lenM[1] ),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _273_ (
    .CLK(clk),
    .D(_010_),
    .Q(\lenM[2] ),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _274_ (
    .CLK(clk),
    .D(_011_),
    .Q(\lenM[3] ),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _275_ (
    .CLK(clk),
    .D(_012_),
    .Q(\DADDR[0] ),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _276_ (
    .CLK(clk),
    .D(_013_),
    .Q(\DADDR[1] ),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _277_ (
    .CLK(clk),
    .D(_014_),
    .Q(\DADDR[2] ),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _278_ (
    .CLK(clk),
    .D(awaddr[0]),
    .Q(\awaddr_pipe[0] ),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _279_ (
    .CLK(clk),
    .D(awaddr[1]),
    .Q(\awaddr_pipe[1] ),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _280_ (
    .CLK(clk),
    .D(awaddr[2]),
    .Q(\awaddr_pipe[2] ),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _281_ (
    .CLK(clk),
    .D(araddr[0]),
    .Q(\araddr_pipe[0] ),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _282_ (
    .CLK(clk),
    .D(araddr[1]),
    .Q(\araddr_pipe[1] ),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _283_ (
    .CLK(clk),
    .D(araddr[2]),
    .Q(\araddr_pipe[2] ),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _284_ (
    .CLK(clk),
    .D(awvalid),
    .Q(awvalid_pipe),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _285_ (
    .CLK(clk),
    .D(arvalid),
    .Q(arvalid_pipe),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _286_ (
    .CLK(clk),
    .D(wvalid),
    .Q(wvalid_pipe),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _287_ (
    .CLK(clk),
    .D(awburst[0]),
    .Q(\awburst_pipe[0] ),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _288_ (
    .CLK(clk),
    .D(awburst[1]),
    .Q(\awburst_pipe[1] ),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _289_ (
    .CLK(clk),
    .D(arburst[0]),
    .Q(\arburst_pipe[0] ),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _290_ (
    .CLK(clk),
    .D(arburst[1]),
    .Q(\arburst_pipe[1] ),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _291_ (
    .CLK(clk),
    .D(awlen[0]),
    .Q(\awlen_pipe[0] ),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _292_ (
    .CLK(clk),
    .D(awlen[1]),
    .Q(\awlen_pipe[1] ),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _293_ (
    .CLK(clk),
    .D(awlen[2]),
    .Q(\awlen_pipe[2] ),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _294_ (
    .CLK(clk),
    .D(awlen[3]),
    .Q(\awlen_pipe[3] ),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _295_ (
    .CLK(clk),
    .D(arlen[0]),
    .Q(\arlen_pipe[0] ),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _296_ (
    .CLK(clk),
    .D(arlen[1]),
    .Q(\arlen_pipe[1] ),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _297_ (
    .CLK(clk),
    .D(arlen[2]),
    .Q(\arlen_pipe[2] ),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _298_ (
    .CLK(clk),
    .D(arlen[3]),
    .Q(\arlen_pipe[3] ),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _299_ (
    .CLK(clk),
    .D(_015_),
    .Q(\current_state[0] ),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _300_ (
    .CLK(clk),
    .D(_016_),
    .Q(\current_state[1] ),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _301_ (
    .CLK(clk),
    .D(_017_),
    .Q(\current_state[2] ),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _302_ (
    .CLK(clk),
    .D(_018_),
    .Q(\current_state[3] ),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__conb_1 _303_ (
    .LO(PSEL1)
  );
  sky130_fd_sc_hd__conb_1 _304_ (
    .LO(PSEL2)
  );
  sky130_fd_sc_hd__conb_1 _305_ (
    .LO(PSEL3)
  );
  sky130_fd_sc_hd__conb_1 _306_ (
    .LO(PSEL4)
  );
  sky130_fd_sc_hd__conb_1 _307_ (
    .LO(PWDATA[0])
  );
  sky130_fd_sc_hd__conb_1 _308_ (
    .LO(PWDATA[1])
  );
  sky130_fd_sc_hd__conb_1 _309_ (
    .LO(PWDATA[2])
  );
  sky130_fd_sc_hd__conb_1 _310_ (
    .LO(PWDATA[3])
  );
  sky130_fd_sc_hd__conb_1 _311_ (
    .LO(PWDATA[4])
  );
  sky130_fd_sc_hd__conb_1 _312_ (
    .LO(PWDATA[5])
  );
  sky130_fd_sc_hd__conb_1 _313_ (
    .LO(PWDATA[6])
  );
  sky130_fd_sc_hd__conb_1 _314_ (
    .LO(PWDATA[7])
  );
  sky130_fd_sc_hd__conb_1 _315_ (
    .LO(PWDATA[8])
  );
  sky130_fd_sc_hd__conb_1 _316_ (
    .LO(PWDATA[9])
  );
  sky130_fd_sc_hd__conb_1 _317_ (
    .LO(PWDATA[10])
  );
  sky130_fd_sc_hd__conb_1 _318_ (
    .LO(PWDATA[11])
  );
  sky130_fd_sc_hd__conb_1 _319_ (
    .LO(PWDATA[12])
  );
  sky130_fd_sc_hd__conb_1 _320_ (
    .LO(PWDATA[13])
  );
  sky130_fd_sc_hd__conb_1 _321_ (
    .LO(PWDATA[14])
  );
  sky130_fd_sc_hd__conb_1 _322_ (
    .LO(PWDATA[15])
  );
  sky130_fd_sc_hd__conb_1 _323_ (
    .LO(rdata[0])
  );
  sky130_fd_sc_hd__conb_1 _324_ (
    .LO(rdata[1])
  );
  sky130_fd_sc_hd__conb_1 _325_ (
    .LO(rdata[2])
  );
  sky130_fd_sc_hd__conb_1 _326_ (
    .LO(rdata[3])
  );
  sky130_fd_sc_hd__conb_1 _327_ (
    .LO(rdata[4])
  );
  sky130_fd_sc_hd__conb_1 _328_ (
    .LO(rdata[5])
  );
  sky130_fd_sc_hd__conb_1 _329_ (
    .LO(rdata[6])
  );
  sky130_fd_sc_hd__conb_1 _330_ (
    .LO(rdata[7])
  );
  sky130_fd_sc_hd__conb_1 _331_ (
    .LO(rdata[8])
  );
  sky130_fd_sc_hd__conb_1 _332_ (
    .LO(rdata[9])
  );
  sky130_fd_sc_hd__conb_1 _333_ (
    .LO(rdata[10])
  );
  sky130_fd_sc_hd__conb_1 _334_ (
    .LO(rdata[11])
  );
  sky130_fd_sc_hd__conb_1 _335_ (
    .LO(rdata[12])
  );
  sky130_fd_sc_hd__conb_1 _336_ (
    .LO(rdata[13])
  );
  sky130_fd_sc_hd__conb_1 _337_ (
    .LO(rdata[14])
  );
  sky130_fd_sc_hd__conb_1 _338_ (
    .LO(rdata[15])
  );
  sky130_fd_sc_hd__buf_2 _339_ (
    .A(bresp),
    .X(bvalid)
  );
  sky130_fd_sc_hd__buf_2 _340_ (
    .A(rresp),
    .X(rvalid)
  );
endmodule
