/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

module bridge(clk, arvalid, res_n, arburst, arlen, araddr, arready, rdata, rresp, rlast, rready, rvalid, awvalid, awaddr, awready, awlen, awburst, wvalid, wdata, wready, wlast
, bready, bvalid, bresp, PADDR, PWDATA, PRDATA, PWRITE, PENABLE, PSEL1, PSEL2, PSEL3, PSEL4, PREADY);
  wire _0000_;
  wire _0001_;
  wire _0002_;
  wire _0003_;
  wire _0004_;
  wire _0005_;
  wire _0006_;
  wire _0007_;
  wire _0008_;
  wire _0009_;
  wire _0010_;
  wire _0011_;
  wire _0012_;
  wire _0013_;
  wire _0014_;
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire _0022_;
  wire _0023_;
  wire _0024_;
  wire _0025_;
  wire _0026_;
  wire _0027_;
  wire _0028_;
  wire _0029_;
  wire _0030_;
  wire _0031_;
  wire _0032_;
  wire _0033_;
  wire _0034_;
  wire _0035_;
  wire _0036_;
  wire _0037_;
  wire _0038_;
  wire _0039_;
  wire _0040_;
  wire _0041_;
  wire _0042_;
  wire _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire _0072_;
  wire _0073_;
  wire _0074_;
  wire _0075_;
  wire _0076_;
  wire _0077_;
  wire _0078_;
  wire _0079_;
  wire _0080_;
  wire _0081_;
  wire _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire _0086_;
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire \DADDR[0] ;
  wire \DADDR[1] ;
  wire \DADDR[2] ;
  wire \DDATA[0][0] ;
  wire \DDATA[0][10] ;
  wire \DDATA[0][11] ;
  wire \DDATA[0][12] ;
  wire \DDATA[0][13] ;
  wire \DDATA[0][14] ;
  wire \DDATA[0][15] ;
  wire \DDATA[0][1] ;
  wire \DDATA[0][2] ;
  wire \DDATA[0][3] ;
  wire \DDATA[0][4] ;
  wire \DDATA[0][5] ;
  wire \DDATA[0][6] ;
  wire \DDATA[0][7] ;
  wire \DDATA[0][8] ;
  wire \DDATA[0][9] ;
  wire \DDATA[10][0] ;
  wire \DDATA[10][10] ;
  wire \DDATA[10][11] ;
  wire \DDATA[10][12] ;
  wire \DDATA[10][13] ;
  wire \DDATA[10][14] ;
  wire \DDATA[10][15] ;
  wire \DDATA[10][1] ;
  wire \DDATA[10][2] ;
  wire \DDATA[10][3] ;
  wire \DDATA[10][4] ;
  wire \DDATA[10][5] ;
  wire \DDATA[10][6] ;
  wire \DDATA[10][7] ;
  wire \DDATA[10][8] ;
  wire \DDATA[10][9] ;
  wire \DDATA[11][0] ;
  wire \DDATA[11][10] ;
  wire \DDATA[11][11] ;
  wire \DDATA[11][12] ;
  wire \DDATA[11][13] ;
  wire \DDATA[11][14] ;
  wire \DDATA[11][15] ;
  wire \DDATA[11][1] ;
  wire \DDATA[11][2] ;
  wire \DDATA[11][3] ;
  wire \DDATA[11][4] ;
  wire \DDATA[11][5] ;
  wire \DDATA[11][6] ;
  wire \DDATA[11][7] ;
  wire \DDATA[11][8] ;
  wire \DDATA[11][9] ;
  wire \DDATA[12][0] ;
  wire \DDATA[12][10] ;
  wire \DDATA[12][11] ;
  wire \DDATA[12][12] ;
  wire \DDATA[12][13] ;
  wire \DDATA[12][14] ;
  wire \DDATA[12][15] ;
  wire \DDATA[12][1] ;
  wire \DDATA[12][2] ;
  wire \DDATA[12][3] ;
  wire \DDATA[12][4] ;
  wire \DDATA[12][5] ;
  wire \DDATA[12][6] ;
  wire \DDATA[12][7] ;
  wire \DDATA[12][8] ;
  wire \DDATA[12][9] ;
  wire \DDATA[13][0] ;
  wire \DDATA[13][10] ;
  wire \DDATA[13][11] ;
  wire \DDATA[13][12] ;
  wire \DDATA[13][13] ;
  wire \DDATA[13][14] ;
  wire \DDATA[13][15] ;
  wire \DDATA[13][1] ;
  wire \DDATA[13][2] ;
  wire \DDATA[13][3] ;
  wire \DDATA[13][4] ;
  wire \DDATA[13][5] ;
  wire \DDATA[13][6] ;
  wire \DDATA[13][7] ;
  wire \DDATA[13][8] ;
  wire \DDATA[13][9] ;
  wire \DDATA[14][0] ;
  wire \DDATA[14][10] ;
  wire \DDATA[14][11] ;
  wire \DDATA[14][12] ;
  wire \DDATA[14][13] ;
  wire \DDATA[14][14] ;
  wire \DDATA[14][15] ;
  wire \DDATA[14][1] ;
  wire \DDATA[14][2] ;
  wire \DDATA[14][3] ;
  wire \DDATA[14][4] ;
  wire \DDATA[14][5] ;
  wire \DDATA[14][6] ;
  wire \DDATA[14][7] ;
  wire \DDATA[14][8] ;
  wire \DDATA[14][9] ;
  wire \DDATA[15][0] ;
  wire \DDATA[15][10] ;
  wire \DDATA[15][11] ;
  wire \DDATA[15][12] ;
  wire \DDATA[15][13] ;
  wire \DDATA[15][14] ;
  wire \DDATA[15][15] ;
  wire \DDATA[15][1] ;
  wire \DDATA[15][2] ;
  wire \DDATA[15][3] ;
  wire \DDATA[15][4] ;
  wire \DDATA[15][5] ;
  wire \DDATA[15][6] ;
  wire \DDATA[15][7] ;
  wire \DDATA[15][8] ;
  wire \DDATA[15][9] ;
  wire \DDATA[1][0] ;
  wire \DDATA[1][10] ;
  wire \DDATA[1][11] ;
  wire \DDATA[1][12] ;
  wire \DDATA[1][13] ;
  wire \DDATA[1][14] ;
  wire \DDATA[1][15] ;
  wire \DDATA[1][1] ;
  wire \DDATA[1][2] ;
  wire \DDATA[1][3] ;
  wire \DDATA[1][4] ;
  wire \DDATA[1][5] ;
  wire \DDATA[1][6] ;
  wire \DDATA[1][7] ;
  wire \DDATA[1][8] ;
  wire \DDATA[1][9] ;
  wire \DDATA[2][0] ;
  wire \DDATA[2][10] ;
  wire \DDATA[2][11] ;
  wire \DDATA[2][12] ;
  wire \DDATA[2][13] ;
  wire \DDATA[2][14] ;
  wire \DDATA[2][15] ;
  wire \DDATA[2][1] ;
  wire \DDATA[2][2] ;
  wire \DDATA[2][3] ;
  wire \DDATA[2][4] ;
  wire \DDATA[2][5] ;
  wire \DDATA[2][6] ;
  wire \DDATA[2][7] ;
  wire \DDATA[2][8] ;
  wire \DDATA[2][9] ;
  wire \DDATA[3][0] ;
  wire \DDATA[3][10] ;
  wire \DDATA[3][11] ;
  wire \DDATA[3][12] ;
  wire \DDATA[3][13] ;
  wire \DDATA[3][14] ;
  wire \DDATA[3][15] ;
  wire \DDATA[3][1] ;
  wire \DDATA[3][2] ;
  wire \DDATA[3][3] ;
  wire \DDATA[3][4] ;
  wire \DDATA[3][5] ;
  wire \DDATA[3][6] ;
  wire \DDATA[3][7] ;
  wire \DDATA[3][8] ;
  wire \DDATA[3][9] ;
  wire \DDATA[4][0] ;
  wire \DDATA[4][10] ;
  wire \DDATA[4][11] ;
  wire \DDATA[4][12] ;
  wire \DDATA[4][13] ;
  wire \DDATA[4][14] ;
  wire \DDATA[4][15] ;
  wire \DDATA[4][1] ;
  wire \DDATA[4][2] ;
  wire \DDATA[4][3] ;
  wire \DDATA[4][4] ;
  wire \DDATA[4][5] ;
  wire \DDATA[4][6] ;
  wire \DDATA[4][7] ;
  wire \DDATA[4][8] ;
  wire \DDATA[4][9] ;
  wire \DDATA[5][0] ;
  wire \DDATA[5][10] ;
  wire \DDATA[5][11] ;
  wire \DDATA[5][12] ;
  wire \DDATA[5][13] ;
  wire \DDATA[5][14] ;
  wire \DDATA[5][15] ;
  wire \DDATA[5][1] ;
  wire \DDATA[5][2] ;
  wire \DDATA[5][3] ;
  wire \DDATA[5][4] ;
  wire \DDATA[5][5] ;
  wire \DDATA[5][6] ;
  wire \DDATA[5][7] ;
  wire \DDATA[5][8] ;
  wire \DDATA[5][9] ;
  wire \DDATA[6][0] ;
  wire \DDATA[6][10] ;
  wire \DDATA[6][11] ;
  wire \DDATA[6][12] ;
  wire \DDATA[6][13] ;
  wire \DDATA[6][14] ;
  wire \DDATA[6][15] ;
  wire \DDATA[6][1] ;
  wire \DDATA[6][2] ;
  wire \DDATA[6][3] ;
  wire \DDATA[6][4] ;
  wire \DDATA[6][5] ;
  wire \DDATA[6][6] ;
  wire \DDATA[6][7] ;
  wire \DDATA[6][8] ;
  wire \DDATA[6][9] ;
  wire \DDATA[7][0] ;
  wire \DDATA[7][10] ;
  wire \DDATA[7][11] ;
  wire \DDATA[7][12] ;
  wire \DDATA[7][13] ;
  wire \DDATA[7][14] ;
  wire \DDATA[7][15] ;
  wire \DDATA[7][1] ;
  wire \DDATA[7][2] ;
  wire \DDATA[7][3] ;
  wire \DDATA[7][4] ;
  wire \DDATA[7][5] ;
  wire \DDATA[7][6] ;
  wire \DDATA[7][7] ;
  wire \DDATA[7][8] ;
  wire \DDATA[7][9] ;
  wire \DDATA[8][0] ;
  wire \DDATA[8][10] ;
  wire \DDATA[8][11] ;
  wire \DDATA[8][12] ;
  wire \DDATA[8][13] ;
  wire \DDATA[8][14] ;
  wire \DDATA[8][15] ;
  wire \DDATA[8][1] ;
  wire \DDATA[8][2] ;
  wire \DDATA[8][3] ;
  wire \DDATA[8][4] ;
  wire \DDATA[8][5] ;
  wire \DDATA[8][6] ;
  wire \DDATA[8][7] ;
  wire \DDATA[8][8] ;
  wire \DDATA[8][9] ;
  wire \DDATA[9][0] ;
  wire \DDATA[9][10] ;
  wire \DDATA[9][11] ;
  wire \DDATA[9][12] ;
  wire \DDATA[9][13] ;
  wire \DDATA[9][14] ;
  wire \DDATA[9][15] ;
  wire \DDATA[9][1] ;
  wire \DDATA[9][2] ;
  wire \DDATA[9][3] ;
  wire \DDATA[9][4] ;
  wire \DDATA[9][5] ;
  wire \DDATA[9][6] ;
  wire \DDATA[9][7] ;
  wire \DDATA[9][8] ;
  wire \DDATA[9][9] ;
  wire \DWREQ[0] ;
  wire \DWREQ[1] ;
  output [2:0] PADDR;
  wire [2:0] PADDR;
  output PENABLE;
  wire PENABLE;
  input [15:0] PRDATA;
  wire [15:0] PRDATA;
  input PREADY;
  wire PREADY;
  output PSEL1;
  wire PSEL1;
  output PSEL2;
  wire PSEL2;
  output PSEL3;
  wire PSEL3;
  output PSEL4;
  wire PSEL4;
  output [15:0] PWDATA;
  wire [15:0] PWDATA;
  output PWRITE;
  wire PWRITE;
  wire \addr[3] ;
  wire \addr[4] ;
  input [4:0] araddr;
  wire [4:0] araddr;
  input [1:0] arburst;
  wire [1:0] arburst;
  input [3:0] arlen;
  wire [3:0] arlen;
  output arready;
  wire arready;
  input arvalid;
  wire arvalid;
  input [4:0] awaddr;
  wire [4:0] awaddr;
  input [1:0] awburst;
  wire [1:0] awburst;
  input [3:0] awlen;
  wire [3:0] awlen;
  output awready;
  wire awready;
  input awvalid;
  wire awvalid;
  input bready;
  wire bready;
  output bresp;
  wire bresp;
  wire \burst[0] ;
  wire \burst[1] ;
  output bvalid;
  wire bvalid;
  input clk;
  wire clk;
  wire \current_state[0] ;
  wire \current_state[1] ;
  wire \current_state[2] ;
  wire \current_state[3] ;
  wire \i[0] ;
  wire \i[1] ;
  wire \i[2] ;
  wire \i[3] ;
  wire last;
  wire \lenM[0] ;
  wire \lenM[1] ;
  wire \lenM[2] ;
  wire \lenM[3] ;
  wire \lenS[0] ;
  wire \lenS[1] ;
  wire \lenS[2] ;
  wire \lenS[3] ;
  output [15:0] rdata;
  wire [15:0] rdata;
  input res_n;
  wire res_n;
  output rlast;
  wire rlast;
  input rready;
  wire rready;
  output rresp;
  wire rresp;
  output rvalid;
  wire rvalid;
  input [15:0] wdata;
  wire [15:0] wdata;
  input wlast;
  wire wlast;
  output wready;
  wire wready;
  input wvalid;
  wire wvalid;
  sky130_fd_sc_hd__inv_2 _0390_ (
    .A(arvalid),
    .Y(_0094_)
  );
  sky130_fd_sc_hd__inv_2 _0391_ (
    .A(rready),
    .Y(_0095_)
  );
  sky130_fd_sc_hd__inv_2 _0392_ (
    .A(awvalid),
    .Y(_0096_)
  );
  sky130_fd_sc_hd__inv_2 _0393_ (
    .A(PREADY),
    .Y(_0097_)
  );
  sky130_fd_sc_hd__and2b_2 _0394_ (
    .A_N(\current_state[2] ),
    .B(\current_state[3] ),
    .X(_0098_)
  );
  sky130_fd_sc_hd__or3b_2 _0395_ (
    .A(\current_state[0] ),
    .B(\current_state[1] ),
    .C_N(_0098_),
    .X(_0099_)
  );
  sky130_fd_sc_hd__inv_2 _0396_ (
    .A(_0099_),
    .Y(wready)
  );
  sky130_fd_sc_hd__nor4_2 _0397_ (
    .A(\i[0] ),
    .B(\i[1] ),
    .C(\i[2] ),
    .D(\i[3] ),
    .Y(_0100_)
  );
  sky130_fd_sc_hd__or4_2 _0398_ (
    .A(\i[0] ),
    .B(\i[1] ),
    .C(\i[2] ),
    .D(\i[3] ),
    .X(_0101_)
  );
  sky130_fd_sc_hd__or3b_2 _0399_ (
    .A(\current_state[0] ),
    .B(\current_state[2] ),
    .C_N(\current_state[1] ),
    .X(_0102_)
  );
  sky130_fd_sc_hd__nor2_2 _0400_ (
    .A(\current_state[3] ),
    .B(_0102_),
    .Y(_0103_)
  );
  sky130_fd_sc_hd__nand2_2 _0401_ (
    .A(PREADY),
    .B(_0103_),
    .Y(_0104_)
  );
  sky130_fd_sc_hd__nor2_2 _0402_ (
    .A(\lenM[0] ),
    .B(\lenM[1] ),
    .Y(_0105_)
  );
  sky130_fd_sc_hd__or3_2 _0403_ (
    .A(\lenM[0] ),
    .B(\lenM[1] ),
    .C(\lenM[2] ),
    .X(_0106_)
  );
  sky130_fd_sc_hd__nor4_2 _0404_ (
    .A(\lenM[0] ),
    .B(\lenM[1] ),
    .C(\lenM[2] ),
    .D(\lenM[3] ),
    .Y(_0107_)
  );
  sky130_fd_sc_hd__inv_2 _0405_ (
    .A(_0107_),
    .Y(_0108_)
  );
  sky130_fd_sc_hd__o21ai_2 _0406_ (
    .A1(_0099_),
    .A2(_0107_),
    .B1(_0104_),
    .Y(_0109_)
  );
  sky130_fd_sc_hd__nand2_2 _0407_ (
    .A(_0100_),
    .B(_0109_),
    .Y(_0059_)
  );
  sky130_fd_sc_hd__nor4b_2 _0408_ (
    .A(\i[1] ),
    .B(\i[2] ),
    .C(\i[3] ),
    .D_N(\i[0] ),
    .Y(_0110_)
  );
  sky130_fd_sc_hd__nand2_2 _0409_ (
    .A(_0109_),
    .B(_0110_),
    .Y(_0060_)
  );
  sky130_fd_sc_hd__nor4b_2 _0410_ (
    .A(\i[0] ),
    .B(\i[2] ),
    .C(\i[3] ),
    .D_N(\i[1] ),
    .Y(_0111_)
  );
  sky130_fd_sc_hd__nand2_2 _0411_ (
    .A(_0109_),
    .B(_0111_),
    .Y(_0061_)
  );
  sky130_fd_sc_hd__and4bb_2 _0412_ (
    .A_N(\i[2] ),
    .B_N(\i[3] ),
    .C(\i[0] ),
    .D(\i[1] ),
    .X(_0112_)
  );
  sky130_fd_sc_hd__nand2_2 _0413_ (
    .A(_0109_),
    .B(_0112_),
    .Y(_0062_)
  );
  sky130_fd_sc_hd__nor4b_2 _0414_ (
    .A(\i[0] ),
    .B(\i[1] ),
    .C(\i[3] ),
    .D_N(\i[2] ),
    .Y(_0113_)
  );
  sky130_fd_sc_hd__nand2_2 _0415_ (
    .A(_0109_),
    .B(_0113_),
    .Y(_0063_)
  );
  sky130_fd_sc_hd__and4bb_2 _0416_ (
    .A_N(\i[1] ),
    .B_N(\i[3] ),
    .C(\i[2] ),
    .D(\i[0] ),
    .X(_0114_)
  );
  sky130_fd_sc_hd__nand2_2 _0417_ (
    .A(_0109_),
    .B(_0114_),
    .Y(_0064_)
  );
  sky130_fd_sc_hd__and4bb_2 _0418_ (
    .A_N(\i[0] ),
    .B_N(\i[3] ),
    .C(\i[2] ),
    .D(\i[1] ),
    .X(_0115_)
  );
  sky130_fd_sc_hd__nand2_2 _0419_ (
    .A(_0109_),
    .B(_0115_),
    .Y(_0065_)
  );
  sky130_fd_sc_hd__and4b_2 _0420_ (
    .A_N(\i[3] ),
    .B(\i[2] ),
    .C(\i[1] ),
    .D(\i[0] ),
    .X(_0116_)
  );
  sky130_fd_sc_hd__nand2_2 _0421_ (
    .A(_0109_),
    .B(_0116_),
    .Y(_0066_)
  );
  sky130_fd_sc_hd__nor4b_2 _0422_ (
    .A(\i[0] ),
    .B(\i[1] ),
    .C(\i[2] ),
    .D_N(\i[3] ),
    .Y(_0117_)
  );
  sky130_fd_sc_hd__nand2_2 _0423_ (
    .A(_0109_),
    .B(_0117_),
    .Y(_0067_)
  );
  sky130_fd_sc_hd__and4bb_2 _0424_ (
    .A_N(\i[1] ),
    .B_N(\i[2] ),
    .C(\i[3] ),
    .D(\i[0] ),
    .X(_0118_)
  );
  sky130_fd_sc_hd__nand2_2 _0425_ (
    .A(_0109_),
    .B(_0118_),
    .Y(_0068_)
  );
  sky130_fd_sc_hd__and4bb_2 _0426_ (
    .A_N(\i[0] ),
    .B_N(\i[2] ),
    .C(\i[3] ),
    .D(\i[1] ),
    .X(_0119_)
  );
  sky130_fd_sc_hd__nand2_2 _0427_ (
    .A(_0109_),
    .B(_0119_),
    .Y(_0069_)
  );
  sky130_fd_sc_hd__and4b_2 _0428_ (
    .A_N(\i[2] ),
    .B(\i[3] ),
    .C(\i[0] ),
    .D(\i[1] ),
    .X(_0120_)
  );
  sky130_fd_sc_hd__nand2_2 _0429_ (
    .A(_0109_),
    .B(_0120_),
    .Y(_0070_)
  );
  sky130_fd_sc_hd__and4bb_2 _0430_ (
    .A_N(\i[0] ),
    .B_N(\i[1] ),
    .C(\i[2] ),
    .D(\i[3] ),
    .X(_0121_)
  );
  sky130_fd_sc_hd__nand2_2 _0431_ (
    .A(_0109_),
    .B(_0121_),
    .Y(_0071_)
  );
  sky130_fd_sc_hd__and4b_2 _0432_ (
    .A_N(\i[1] ),
    .B(\i[2] ),
    .C(\i[3] ),
    .D(\i[0] ),
    .X(_0122_)
  );
  sky130_fd_sc_hd__nand2_2 _0433_ (
    .A(_0109_),
    .B(_0122_),
    .Y(_0072_)
  );
  sky130_fd_sc_hd__and4b_2 _0434_ (
    .A_N(\i[0] ),
    .B(\i[1] ),
    .C(\i[2] ),
    .D(\i[3] ),
    .X(_0123_)
  );
  sky130_fd_sc_hd__nand2_2 _0435_ (
    .A(_0109_),
    .B(_0123_),
    .Y(_0073_)
  );
  sky130_fd_sc_hd__and4_2 _0436_ (
    .A(\i[0] ),
    .B(\i[1] ),
    .C(\i[2] ),
    .D(\i[3] ),
    .X(_0124_)
  );
  sky130_fd_sc_hd__nand2_2 _0437_ (
    .A(_0109_),
    .B(_0124_),
    .Y(_0074_)
  );
  sky130_fd_sc_hd__or4b_2 _0438_ (
    .A(\current_state[1] ),
    .B(\current_state[2] ),
    .C(\current_state[3] ),
    .D_N(\current_state[0] ),
    .X(_0125_)
  );
  sky130_fd_sc_hd__inv_2 _0439_ (
    .A(_0125_),
    .Y(arready)
  );
  sky130_fd_sc_hd__nand2_2 _0440_ (
    .A(\current_state[0] ),
    .B(\current_state[1] ),
    .Y(_0126_)
  );
  sky130_fd_sc_hd__and3b_2 _0441_ (
    .A_N(\current_state[2] ),
    .B(\current_state[1] ),
    .C(\current_state[0] ),
    .X(_0127_)
  );
  sky130_fd_sc_hd__nand3b_2 _0442_ (
    .A_N(\current_state[2] ),
    .B(\current_state[1] ),
    .C(\current_state[0] ),
    .Y(_0128_)
  );
  sky130_fd_sc_hd__nor2_2 _0443_ (
    .A(arready),
    .B(_0127_),
    .Y(_0129_)
  );
  sky130_fd_sc_hd__nand2_2 _0444_ (
    .A(_0125_),
    .B(_0128_),
    .Y(_0130_)
  );
  sky130_fd_sc_hd__nand2_2 _0445_ (
    .A(_0102_),
    .B(_0129_),
    .Y(_0131_)
  );
  sky130_fd_sc_hd__a211oi_2 _0446_ (
    .A1(_0102_),
    .A2(_0129_),
    .B1(\addr[3] ),
    .C1(\addr[4] ),
    .Y(PSEL1)
  );
  sky130_fd_sc_hd__and3b_2 _0447_ (
    .A_N(\addr[4] ),
    .B(_0131_),
    .C(\addr[3] ),
    .X(PSEL2)
  );
  sky130_fd_sc_hd__and3b_2 _0448_ (
    .A_N(\addr[3] ),
    .B(\addr[4] ),
    .C(_0131_),
    .X(PSEL3)
  );
  sky130_fd_sc_hd__and3_2 _0449_ (
    .A(\addr[3] ),
    .B(\addr[4] ),
    .C(_0131_),
    .X(PSEL4)
  );
  sky130_fd_sc_hd__and2_2 _0450_ (
    .A(\DWREQ[1] ),
    .B(_0131_),
    .X(PWRITE)
  );
  sky130_fd_sc_hd__or2_2 _0451_ (
    .A(_0103_),
    .B(_0127_),
    .X(PENABLE)
  );
  sky130_fd_sc_hd__nand2b_2 _0452_ (
    .A_N(\current_state[3] ),
    .B(\current_state[2] ),
    .Y(_0132_)
  );
  sky130_fd_sc_hd__or4bb_2 _0453_ (
    .A(\current_state[1] ),
    .B(\current_state[3] ),
    .C_N(\current_state[2] ),
    .D_N(\current_state[0] ),
    .X(_0133_)
  );
  sky130_fd_sc_hd__inv_2 _0454_ (
    .A(_0133_),
    .Y(rresp)
  );
  sky130_fd_sc_hd__and2_2 _0455_ (
    .A(last),
    .B(rresp),
    .X(rlast)
  );
  sky130_fd_sc_hd__and2_2 _0456_ (
    .A(\DWREQ[0] ),
    .B(\DADDR[0] ),
    .X(PADDR[0])
  );
  sky130_fd_sc_hd__and2_2 _0457_ (
    .A(\DWREQ[0] ),
    .B(\DADDR[1] ),
    .X(PADDR[1])
  );
  sky130_fd_sc_hd__and2_2 _0458_ (
    .A(\DWREQ[0] ),
    .B(\DADDR[2] ),
    .X(PADDR[2])
  );
  sky130_fd_sc_hd__and3b_2 _0459_ (
    .A_N(\current_state[1] ),
    .B(_0098_),
    .C(\current_state[0] ),
    .X(bresp)
  );
  sky130_fd_sc_hd__or2_2 _0460_ (
    .A(arvalid),
    .B(bresp),
    .X(_0016_)
  );
  sky130_fd_sc_hd__and4b_2 _0461_ (
    .A_N(\current_state[2] ),
    .B(\current_state[3] ),
    .C(\current_state[0] ),
    .D(\current_state[1] ),
    .X(_0134_)
  );
  sky130_fd_sc_hd__nand4b_2 _0462_ (
    .A_N(\current_state[2] ),
    .B(\current_state[3] ),
    .C(\current_state[0] ),
    .D(\current_state[1] ),
    .Y(_0135_)
  );
  sky130_fd_sc_hd__a22o_2 _0463_ (
    .A1(\DDATA[7][0] ),
    .A2(_0116_),
    .B1(_0123_),
    .B2(\DDATA[14][0] ),
    .X(_0136_)
  );
  sky130_fd_sc_hd__a221o_2 _0464_ (
    .A1(\DDATA[4][0] ),
    .A2(_0113_),
    .B1(_0122_),
    .B2(\DDATA[13][0] ),
    .C1(_0136_),
    .X(_0137_)
  );
  sky130_fd_sc_hd__a22o_2 _0465_ (
    .A1(\DDATA[5][0] ),
    .A2(_0114_),
    .B1(_0115_),
    .B2(\DDATA[6][0] ),
    .X(_0138_)
  );
  sky130_fd_sc_hd__a221o_2 _0466_ (
    .A1(\DDATA[12][0] ),
    .A2(_0121_),
    .B1(_0124_),
    .B2(\DDATA[15][0] ),
    .C1(_0138_),
    .X(_0139_)
  );
  sky130_fd_sc_hd__a22o_2 _0467_ (
    .A1(\DDATA[10][0] ),
    .A2(_0119_),
    .B1(_0120_),
    .B2(\DDATA[11][0] ),
    .X(_0140_)
  );
  sky130_fd_sc_hd__a221o_2 _0468_ (
    .A1(\DDATA[1][0] ),
    .A2(_0110_),
    .B1(_0112_),
    .B2(\DDATA[3][0] ),
    .C1(_0140_),
    .X(_0141_)
  );
  sky130_fd_sc_hd__a22o_2 _0469_ (
    .A1(\DDATA[2][0] ),
    .A2(_0111_),
    .B1(_0118_),
    .B2(\DDATA[9][0] ),
    .X(_0142_)
  );
  sky130_fd_sc_hd__a211o_2 _0470_ (
    .A1(\DDATA[8][0] ),
    .A2(_0117_),
    .B1(_0142_),
    .C1(_0100_),
    .X(_0143_)
  );
  sky130_fd_sc_hd__or3_2 _0471_ (
    .A(_0139_),
    .B(_0141_),
    .C(_0143_),
    .X(_0144_)
  );
  sky130_fd_sc_hd__o22ai_2 _0472_ (
    .A1(\DDATA[0][0] ),
    .A2(_0101_),
    .B1(_0137_),
    .B2(_0144_),
    .Y(_0145_)
  );
  sky130_fd_sc_hd__nor2_2 _0473_ (
    .A(_0135_),
    .B(_0145_),
    .Y(_0017_)
  );
  sky130_fd_sc_hd__a22o_2 _0474_ (
    .A1(\DDATA[10][1] ),
    .A2(_0119_),
    .B1(_0120_),
    .B2(\DDATA[11][1] ),
    .X(_0146_)
  );
  sky130_fd_sc_hd__a22o_2 _0475_ (
    .A1(\DDATA[4][1] ),
    .A2(_0113_),
    .B1(_0122_),
    .B2(\DDATA[13][1] ),
    .X(_0147_)
  );
  sky130_fd_sc_hd__a221o_2 _0476_ (
    .A1(\DDATA[1][1] ),
    .A2(_0110_),
    .B1(_0115_),
    .B2(\DDATA[6][1] ),
    .C1(_0147_),
    .X(_0148_)
  );
  sky130_fd_sc_hd__a22o_2 _0477_ (
    .A1(\DDATA[2][1] ),
    .A2(_0111_),
    .B1(_0114_),
    .B2(\DDATA[5][1] ),
    .X(_0149_)
  );
  sky130_fd_sc_hd__a221o_2 _0478_ (
    .A1(\DDATA[3][1] ),
    .A2(_0112_),
    .B1(_0116_),
    .B2(\DDATA[7][1] ),
    .C1(_0149_),
    .X(_0150_)
  );
  sky130_fd_sc_hd__a22o_2 _0479_ (
    .A1(\DDATA[12][1] ),
    .A2(_0121_),
    .B1(_0123_),
    .B2(\DDATA[14][1] ),
    .X(_0151_)
  );
  sky130_fd_sc_hd__a221o_2 _0480_ (
    .A1(\DDATA[9][1] ),
    .A2(_0118_),
    .B1(_0124_),
    .B2(\DDATA[15][1] ),
    .C1(_0100_),
    .X(_0152_)
  );
  sky130_fd_sc_hd__a211o_2 _0481_ (
    .A1(\DDATA[8][1] ),
    .A2(_0117_),
    .B1(_0146_),
    .C1(_0152_),
    .X(_0153_)
  );
  sky130_fd_sc_hd__or3_2 _0482_ (
    .A(_0150_),
    .B(_0151_),
    .C(_0153_),
    .X(_0154_)
  );
  sky130_fd_sc_hd__o22ai_2 _0483_ (
    .A1(\DDATA[0][1] ),
    .A2(_0101_),
    .B1(_0148_),
    .B2(_0154_),
    .Y(_0155_)
  );
  sky130_fd_sc_hd__nor2_2 _0484_ (
    .A(_0135_),
    .B(_0155_),
    .Y(_0024_)
  );
  sky130_fd_sc_hd__a22o_2 _0485_ (
    .A1(\DDATA[7][2] ),
    .A2(_0116_),
    .B1(_0124_),
    .B2(\DDATA[15][2] ),
    .X(_0156_)
  );
  sky130_fd_sc_hd__a221o_2 _0486_ (
    .A1(\DDATA[5][2] ),
    .A2(_0114_),
    .B1(_0122_),
    .B2(\DDATA[13][2] ),
    .C1(_0156_),
    .X(_0157_)
  );
  sky130_fd_sc_hd__a22o_2 _0487_ (
    .A1(\DDATA[4][2] ),
    .A2(_0113_),
    .B1(_0121_),
    .B2(\DDATA[12][2] ),
    .X(_0158_)
  );
  sky130_fd_sc_hd__a221o_2 _0488_ (
    .A1(\DDATA[6][2] ),
    .A2(_0115_),
    .B1(_0123_),
    .B2(\DDATA[14][2] ),
    .C1(_0158_),
    .X(_0159_)
  );
  sky130_fd_sc_hd__a22o_2 _0489_ (
    .A1(\DDATA[8][2] ),
    .A2(_0117_),
    .B1(_0118_),
    .B2(\DDATA[9][2] ),
    .X(_0160_)
  );
  sky130_fd_sc_hd__a221o_2 _0490_ (
    .A1(\DDATA[2][2] ),
    .A2(_0111_),
    .B1(_0112_),
    .B2(\DDATA[3][2] ),
    .C1(_0160_),
    .X(_0161_)
  );
  sky130_fd_sc_hd__a22o_2 _0491_ (
    .A1(\DDATA[1][2] ),
    .A2(_0110_),
    .B1(_0119_),
    .B2(\DDATA[10][2] ),
    .X(_0162_)
  );
  sky130_fd_sc_hd__a211o_2 _0492_ (
    .A1(\DDATA[11][2] ),
    .A2(_0120_),
    .B1(_0162_),
    .C1(_0100_),
    .X(_0163_)
  );
  sky130_fd_sc_hd__or3_2 _0493_ (
    .A(_0159_),
    .B(_0161_),
    .C(_0163_),
    .X(_0164_)
  );
  sky130_fd_sc_hd__o22ai_2 _0494_ (
    .A1(\DDATA[0][2] ),
    .A2(_0101_),
    .B1(_0157_),
    .B2(_0164_),
    .Y(_0165_)
  );
  sky130_fd_sc_hd__nor2_2 _0495_ (
    .A(_0135_),
    .B(_0165_),
    .Y(_0025_)
  );
  sky130_fd_sc_hd__a22o_2 _0496_ (
    .A1(\DDATA[4][3] ),
    .A2(_0113_),
    .B1(_0121_),
    .B2(\DDATA[12][3] ),
    .X(_0166_)
  );
  sky130_fd_sc_hd__a221o_2 _0497_ (
    .A1(\DDATA[13][3] ),
    .A2(_0122_),
    .B1(_0124_),
    .B2(\DDATA[15][3] ),
    .C1(_0166_),
    .X(_0167_)
  );
  sky130_fd_sc_hd__a22o_2 _0498_ (
    .A1(\DDATA[5][3] ),
    .A2(_0114_),
    .B1(_0116_),
    .B2(\DDATA[7][3] ),
    .X(_0168_)
  );
  sky130_fd_sc_hd__a221o_2 _0499_ (
    .A1(\DDATA[6][3] ),
    .A2(_0115_),
    .B1(_0123_),
    .B2(\DDATA[14][3] ),
    .C1(_0168_),
    .X(_0169_)
  );
  sky130_fd_sc_hd__a22o_2 _0500_ (
    .A1(\DDATA[2][3] ),
    .A2(_0111_),
    .B1(_0117_),
    .B2(\DDATA[8][3] ),
    .X(_0170_)
  );
  sky130_fd_sc_hd__a221o_2 _0501_ (
    .A1(\DDATA[3][3] ),
    .A2(_0112_),
    .B1(_0120_),
    .B2(\DDATA[11][3] ),
    .C1(_0170_),
    .X(_0171_)
  );
  sky130_fd_sc_hd__a22o_2 _0502_ (
    .A1(\DDATA[1][3] ),
    .A2(_0110_),
    .B1(_0118_),
    .B2(\DDATA[9][3] ),
    .X(_0172_)
  );
  sky130_fd_sc_hd__a211o_2 _0503_ (
    .A1(\DDATA[10][3] ),
    .A2(_0119_),
    .B1(_0172_),
    .C1(_0100_),
    .X(_0173_)
  );
  sky130_fd_sc_hd__or3_2 _0504_ (
    .A(_0169_),
    .B(_0171_),
    .C(_0173_),
    .X(_0174_)
  );
  sky130_fd_sc_hd__o22ai_2 _0505_ (
    .A1(\DDATA[0][3] ),
    .A2(_0101_),
    .B1(_0167_),
    .B2(_0174_),
    .Y(_0175_)
  );
  sky130_fd_sc_hd__nor2_2 _0506_ (
    .A(_0135_),
    .B(_0175_),
    .Y(_0026_)
  );
  sky130_fd_sc_hd__a22o_2 _0507_ (
    .A1(\DDATA[2][4] ),
    .A2(_0111_),
    .B1(_0121_),
    .B2(\DDATA[12][4] ),
    .X(_0176_)
  );
  sky130_fd_sc_hd__a22o_2 _0508_ (
    .A1(\DDATA[14][4] ),
    .A2(_0123_),
    .B1(_0124_),
    .B2(\DDATA[15][4] ),
    .X(_0177_)
  );
  sky130_fd_sc_hd__a22o_2 _0509_ (
    .A1(\DDATA[5][4] ),
    .A2(_0114_),
    .B1(_0122_),
    .B2(\DDATA[13][4] ),
    .X(_0178_)
  );
  sky130_fd_sc_hd__a221o_2 _0510_ (
    .A1(\DDATA[4][4] ),
    .A2(_0113_),
    .B1(_0115_),
    .B2(\DDATA[6][4] ),
    .C1(_0178_),
    .X(_0179_)
  );
  sky130_fd_sc_hd__a22o_2 _0511_ (
    .A1(\DDATA[3][4] ),
    .A2(_0112_),
    .B1(_0116_),
    .B2(\DDATA[7][4] ),
    .X(_0180_)
  );
  sky130_fd_sc_hd__a22o_2 _0512_ (
    .A1(\DDATA[8][4] ),
    .A2(_0117_),
    .B1(_0119_),
    .B2(\DDATA[10][4] ),
    .X(_0181_)
  );
  sky130_fd_sc_hd__a221o_2 _0513_ (
    .A1(\DDATA[1][4] ),
    .A2(_0110_),
    .B1(_0118_),
    .B2(\DDATA[9][4] ),
    .C1(_0100_),
    .X(_0182_)
  );
  sky130_fd_sc_hd__a211o_2 _0514_ (
    .A1(\DDATA[11][4] ),
    .A2(_0120_),
    .B1(_0181_),
    .C1(_0182_),
    .X(_0183_)
  );
  sky130_fd_sc_hd__or4_2 _0515_ (
    .A(_0177_),
    .B(_0179_),
    .C(_0180_),
    .D(_0183_),
    .X(_0184_)
  );
  sky130_fd_sc_hd__o22ai_2 _0516_ (
    .A1(\DDATA[0][4] ),
    .A2(_0101_),
    .B1(_0176_),
    .B2(_0184_),
    .Y(_0185_)
  );
  sky130_fd_sc_hd__nor2_2 _0517_ (
    .A(_0135_),
    .B(_0185_),
    .Y(_0027_)
  );
  sky130_fd_sc_hd__a22o_2 _0518_ (
    .A1(\DDATA[14][5] ),
    .A2(_0123_),
    .B1(_0124_),
    .B2(\DDATA[15][5] ),
    .X(_0186_)
  );
  sky130_fd_sc_hd__a221o_2 _0519_ (
    .A1(\DDATA[12][5] ),
    .A2(_0121_),
    .B1(_0122_),
    .B2(\DDATA[13][5] ),
    .C1(_0186_),
    .X(_0187_)
  );
  sky130_fd_sc_hd__a22o_2 _0520_ (
    .A1(\DDATA[5][5] ),
    .A2(_0114_),
    .B1(_0116_),
    .B2(\DDATA[7][5] ),
    .X(_0188_)
  );
  sky130_fd_sc_hd__a221o_2 _0521_ (
    .A1(\DDATA[4][5] ),
    .A2(_0113_),
    .B1(_0115_),
    .B2(\DDATA[6][5] ),
    .C1(_0188_),
    .X(_0189_)
  );
  sky130_fd_sc_hd__a22o_2 _0522_ (
    .A1(\DDATA[8][5] ),
    .A2(_0117_),
    .B1(_0119_),
    .B2(\DDATA[10][5] ),
    .X(_0190_)
  );
  sky130_fd_sc_hd__a221o_2 _0523_ (
    .A1(\DDATA[1][5] ),
    .A2(_0110_),
    .B1(_0111_),
    .B2(\DDATA[2][5] ),
    .C1(_0190_),
    .X(_0191_)
  );
  sky130_fd_sc_hd__a22o_2 _0524_ (
    .A1(\DDATA[9][5] ),
    .A2(_0118_),
    .B1(_0120_),
    .B2(\DDATA[11][5] ),
    .X(_0192_)
  );
  sky130_fd_sc_hd__a211o_2 _0525_ (
    .A1(\DDATA[3][5] ),
    .A2(_0112_),
    .B1(_0192_),
    .C1(_0100_),
    .X(_0193_)
  );
  sky130_fd_sc_hd__or3_2 _0526_ (
    .A(_0189_),
    .B(_0191_),
    .C(_0193_),
    .X(_0194_)
  );
  sky130_fd_sc_hd__o22ai_2 _0527_ (
    .A1(\DDATA[0][5] ),
    .A2(_0101_),
    .B1(_0187_),
    .B2(_0194_),
    .Y(_0195_)
  );
  sky130_fd_sc_hd__nor2_2 _0528_ (
    .A(_0135_),
    .B(_0195_),
    .Y(_0028_)
  );
  sky130_fd_sc_hd__a22o_2 _0529_ (
    .A1(\DDATA[13][6] ),
    .A2(_0122_),
    .B1(_0123_),
    .B2(\DDATA[14][6] ),
    .X(_0196_)
  );
  sky130_fd_sc_hd__a221o_2 _0530_ (
    .A1(\DDATA[5][6] ),
    .A2(_0114_),
    .B1(_0124_),
    .B2(\DDATA[15][6] ),
    .C1(_0196_),
    .X(_0197_)
  );
  sky130_fd_sc_hd__a22o_2 _0531_ (
    .A1(\DDATA[4][6] ),
    .A2(_0113_),
    .B1(_0116_),
    .B2(\DDATA[7][6] ),
    .X(_0198_)
  );
  sky130_fd_sc_hd__a221o_2 _0532_ (
    .A1(\DDATA[6][6] ),
    .A2(_0115_),
    .B1(_0121_),
    .B2(\DDATA[12][6] ),
    .C1(_0198_),
    .X(_0199_)
  );
  sky130_fd_sc_hd__a22o_2 _0533_ (
    .A1(\DDATA[1][6] ),
    .A2(_0110_),
    .B1(_0120_),
    .B2(\DDATA[11][6] ),
    .X(_0200_)
  );
  sky130_fd_sc_hd__a221o_2 _0534_ (
    .A1(\DDATA[2][6] ),
    .A2(_0111_),
    .B1(_0118_),
    .B2(\DDATA[9][6] ),
    .C1(_0200_),
    .X(_0201_)
  );
  sky130_fd_sc_hd__a22o_2 _0535_ (
    .A1(\DDATA[3][6] ),
    .A2(_0112_),
    .B1(_0117_),
    .B2(\DDATA[8][6] ),
    .X(_0202_)
  );
  sky130_fd_sc_hd__a211o_2 _0536_ (
    .A1(\DDATA[10][6] ),
    .A2(_0119_),
    .B1(_0202_),
    .C1(_0100_),
    .X(_0203_)
  );
  sky130_fd_sc_hd__or3_2 _0537_ (
    .A(_0199_),
    .B(_0201_),
    .C(_0203_),
    .X(_0204_)
  );
  sky130_fd_sc_hd__o22ai_2 _0538_ (
    .A1(\DDATA[0][6] ),
    .A2(_0101_),
    .B1(_0197_),
    .B2(_0204_),
    .Y(_0205_)
  );
  sky130_fd_sc_hd__nor2_2 _0539_ (
    .A(_0135_),
    .B(_0205_),
    .Y(_0029_)
  );
  sky130_fd_sc_hd__a22o_2 _0540_ (
    .A1(\DDATA[6][7] ),
    .A2(_0115_),
    .B1(_0123_),
    .B2(\DDATA[14][7] ),
    .X(_0206_)
  );
  sky130_fd_sc_hd__a221o_2 _0541_ (
    .A1(\DDATA[7][7] ),
    .A2(_0116_),
    .B1(_0122_),
    .B2(\DDATA[13][7] ),
    .C1(_0206_),
    .X(_0207_)
  );
  sky130_fd_sc_hd__a22o_2 _0542_ (
    .A1(\DDATA[12][7] ),
    .A2(_0121_),
    .B1(_0124_),
    .B2(\DDATA[15][7] ),
    .X(_0208_)
  );
  sky130_fd_sc_hd__a221o_2 _0543_ (
    .A1(\DDATA[4][7] ),
    .A2(_0113_),
    .B1(_0114_),
    .B2(\DDATA[5][7] ),
    .C1(_0208_),
    .X(_0209_)
  );
  sky130_fd_sc_hd__a22o_2 _0544_ (
    .A1(\DDATA[2][7] ),
    .A2(_0111_),
    .B1(_0118_),
    .B2(\DDATA[9][7] ),
    .X(_0210_)
  );
  sky130_fd_sc_hd__a221o_2 _0545_ (
    .A1(\DDATA[1][7] ),
    .A2(_0110_),
    .B1(_0120_),
    .B2(\DDATA[11][7] ),
    .C1(_0210_),
    .X(_0211_)
  );
  sky130_fd_sc_hd__a22o_2 _0546_ (
    .A1(\DDATA[3][7] ),
    .A2(_0112_),
    .B1(_0117_),
    .B2(\DDATA[8][7] ),
    .X(_0212_)
  );
  sky130_fd_sc_hd__a211o_2 _0547_ (
    .A1(\DDATA[10][7] ),
    .A2(_0119_),
    .B1(_0212_),
    .C1(_0100_),
    .X(_0213_)
  );
  sky130_fd_sc_hd__or3_2 _0548_ (
    .A(_0209_),
    .B(_0211_),
    .C(_0213_),
    .X(_0214_)
  );
  sky130_fd_sc_hd__o22ai_2 _0549_ (
    .A1(\DDATA[0][7] ),
    .A2(_0101_),
    .B1(_0207_),
    .B2(_0214_),
    .Y(_0215_)
  );
  sky130_fd_sc_hd__nor2_2 _0550_ (
    .A(_0135_),
    .B(_0215_),
    .Y(_0030_)
  );
  sky130_fd_sc_hd__a22o_2 _0551_ (
    .A1(\DDATA[12][8] ),
    .A2(_0121_),
    .B1(_0124_),
    .B2(\DDATA[15][8] ),
    .X(_0216_)
  );
  sky130_fd_sc_hd__a221o_2 _0552_ (
    .A1(\DDATA[2][8] ),
    .A2(_0111_),
    .B1(_0115_),
    .B2(\DDATA[6][8] ),
    .C1(_0216_),
    .X(_0217_)
  );
  sky130_fd_sc_hd__a22o_2 _0553_ (
    .A1(\DDATA[3][8] ),
    .A2(_0112_),
    .B1(_0113_),
    .B2(\DDATA[4][8] ),
    .X(_0218_)
  );
  sky130_fd_sc_hd__a22o_2 _0554_ (
    .A1(\DDATA[8][8] ),
    .A2(_0117_),
    .B1(_0119_),
    .B2(\DDATA[10][8] ),
    .X(_0219_)
  );
  sky130_fd_sc_hd__a221o_2 _0555_ (
    .A1(\DDATA[1][8] ),
    .A2(_0110_),
    .B1(_0118_),
    .B2(\DDATA[9][8] ),
    .C1(_0100_),
    .X(_0220_)
  );
  sky130_fd_sc_hd__a211o_2 _0556_ (
    .A1(\DDATA[11][8] ),
    .A2(_0120_),
    .B1(_0219_),
    .C1(_0220_),
    .X(_0221_)
  );
  sky130_fd_sc_hd__or3_2 _0557_ (
    .A(_0217_),
    .B(_0218_),
    .C(_0221_),
    .X(_0222_)
  );
  sky130_fd_sc_hd__a22o_2 _0558_ (
    .A1(\DDATA[13][8] ),
    .A2(_0122_),
    .B1(_0123_),
    .B2(\DDATA[14][8] ),
    .X(_0223_)
  );
  sky130_fd_sc_hd__a221o_2 _0559_ (
    .A1(\DDATA[5][8] ),
    .A2(_0114_),
    .B1(_0116_),
    .B2(\DDATA[7][8] ),
    .C1(_0223_),
    .X(_0224_)
  );
  sky130_fd_sc_hd__o22ai_2 _0560_ (
    .A1(\DDATA[0][8] ),
    .A2(_0101_),
    .B1(_0222_),
    .B2(_0224_),
    .Y(_0225_)
  );
  sky130_fd_sc_hd__nor2_2 _0561_ (
    .A(_0135_),
    .B(_0225_),
    .Y(_0031_)
  );
  sky130_fd_sc_hd__a22o_2 _0562_ (
    .A1(\DDATA[12][9] ),
    .A2(_0121_),
    .B1(_0124_),
    .B2(\DDATA[15][9] ),
    .X(_0226_)
  );
  sky130_fd_sc_hd__a221o_2 _0563_ (
    .A1(\DDATA[7][9] ),
    .A2(_0116_),
    .B1(_0123_),
    .B2(\DDATA[14][9] ),
    .C1(_0226_),
    .X(_0227_)
  );
  sky130_fd_sc_hd__a22o_2 _0564_ (
    .A1(\DDATA[4][9] ),
    .A2(_0113_),
    .B1(_0115_),
    .B2(\DDATA[6][9] ),
    .X(_0228_)
  );
  sky130_fd_sc_hd__a221o_2 _0565_ (
    .A1(\DDATA[5][9] ),
    .A2(_0114_),
    .B1(_0122_),
    .B2(\DDATA[13][9] ),
    .C1(_0228_),
    .X(_0229_)
  );
  sky130_fd_sc_hd__a22o_2 _0566_ (
    .A1(\DDATA[10][9] ),
    .A2(_0119_),
    .B1(_0120_),
    .B2(\DDATA[11][9] ),
    .X(_0230_)
  );
  sky130_fd_sc_hd__a221o_2 _0567_ (
    .A1(\DDATA[3][9] ),
    .A2(_0112_),
    .B1(_0118_),
    .B2(\DDATA[9][9] ),
    .C1(_0230_),
    .X(_0231_)
  );
  sky130_fd_sc_hd__a22o_2 _0568_ (
    .A1(\DDATA[1][9] ),
    .A2(_0110_),
    .B1(_0111_),
    .B2(\DDATA[2][9] ),
    .X(_0232_)
  );
  sky130_fd_sc_hd__a211o_2 _0569_ (
    .A1(\DDATA[8][9] ),
    .A2(_0117_),
    .B1(_0232_),
    .C1(_0100_),
    .X(_0233_)
  );
  sky130_fd_sc_hd__or3_2 _0570_ (
    .A(_0229_),
    .B(_0231_),
    .C(_0233_),
    .X(_0234_)
  );
  sky130_fd_sc_hd__o22ai_2 _0571_ (
    .A1(\DDATA[0][9] ),
    .A2(_0101_),
    .B1(_0227_),
    .B2(_0234_),
    .Y(_0235_)
  );
  sky130_fd_sc_hd__nor2_2 _0572_ (
    .A(_0135_),
    .B(_0235_),
    .Y(_0032_)
  );
  sky130_fd_sc_hd__a22o_2 _0573_ (
    .A1(\DDATA[5][10] ),
    .A2(_0114_),
    .B1(_0115_),
    .B2(\DDATA[6][10] ),
    .X(_0236_)
  );
  sky130_fd_sc_hd__a221o_2 _0574_ (
    .A1(\DDATA[7][10] ),
    .A2(_0116_),
    .B1(_0123_),
    .B2(\DDATA[14][10] ),
    .C1(_0236_),
    .X(_0237_)
  );
  sky130_fd_sc_hd__a22o_2 _0575_ (
    .A1(\DDATA[4][10] ),
    .A2(_0113_),
    .B1(_0122_),
    .B2(\DDATA[13][10] ),
    .X(_0238_)
  );
  sky130_fd_sc_hd__a221o_2 _0576_ (
    .A1(\DDATA[12][10] ),
    .A2(_0121_),
    .B1(_0124_),
    .B2(\DDATA[15][10] ),
    .C1(_0238_),
    .X(_0239_)
  );
  sky130_fd_sc_hd__a22o_2 _0577_ (
    .A1(\DDATA[9][10] ),
    .A2(_0118_),
    .B1(_0120_),
    .B2(\DDATA[11][10] ),
    .X(_0240_)
  );
  sky130_fd_sc_hd__a221o_2 _0578_ (
    .A1(\DDATA[1][10] ),
    .A2(_0110_),
    .B1(_0112_),
    .B2(\DDATA[3][10] ),
    .C1(_0240_),
    .X(_0241_)
  );
  sky130_fd_sc_hd__a22o_2 _0579_ (
    .A1(\DDATA[2][10] ),
    .A2(_0111_),
    .B1(_0117_),
    .B2(\DDATA[8][10] ),
    .X(_0242_)
  );
  sky130_fd_sc_hd__a211o_2 _0580_ (
    .A1(\DDATA[10][10] ),
    .A2(_0119_),
    .B1(_0242_),
    .C1(_0100_),
    .X(_0243_)
  );
  sky130_fd_sc_hd__or3_2 _0581_ (
    .A(_0239_),
    .B(_0241_),
    .C(_0243_),
    .X(_0244_)
  );
  sky130_fd_sc_hd__o22ai_2 _0582_ (
    .A1(\DDATA[0][10] ),
    .A2(_0101_),
    .B1(_0237_),
    .B2(_0244_),
    .Y(_0245_)
  );
  sky130_fd_sc_hd__nor2_2 _0583_ (
    .A(_0135_),
    .B(_0245_),
    .Y(_0018_)
  );
  sky130_fd_sc_hd__a22o_2 _0584_ (
    .A1(\DDATA[12][11] ),
    .A2(_0121_),
    .B1(_0122_),
    .B2(\DDATA[13][11] ),
    .X(_0246_)
  );
  sky130_fd_sc_hd__a221o_2 _0585_ (
    .A1(\DDATA[4][11] ),
    .A2(_0113_),
    .B1(_0116_),
    .B2(\DDATA[7][11] ),
    .C1(_0246_),
    .X(_0247_)
  );
  sky130_fd_sc_hd__a22o_2 _0586_ (
    .A1(\DDATA[6][11] ),
    .A2(_0115_),
    .B1(_0123_),
    .B2(\DDATA[14][11] ),
    .X(_0248_)
  );
  sky130_fd_sc_hd__a221o_2 _0587_ (
    .A1(\DDATA[5][11] ),
    .A2(_0114_),
    .B1(_0124_),
    .B2(\DDATA[15][11] ),
    .C1(_0248_),
    .X(_0249_)
  );
  sky130_fd_sc_hd__a22o_2 _0588_ (
    .A1(\DDATA[3][11] ),
    .A2(_0112_),
    .B1(_0120_),
    .B2(\DDATA[11][11] ),
    .X(_0250_)
  );
  sky130_fd_sc_hd__a221o_2 _0589_ (
    .A1(\DDATA[1][11] ),
    .A2(_0110_),
    .B1(_0118_),
    .B2(\DDATA[9][11] ),
    .C1(_0250_),
    .X(_0251_)
  );
  sky130_fd_sc_hd__a22o_2 _0590_ (
    .A1(\DDATA[2][11] ),
    .A2(_0111_),
    .B1(_0119_),
    .B2(\DDATA[10][11] ),
    .X(_0252_)
  );
  sky130_fd_sc_hd__a211o_2 _0591_ (
    .A1(\DDATA[8][11] ),
    .A2(_0117_),
    .B1(_0252_),
    .C1(_0100_),
    .X(_0253_)
  );
  sky130_fd_sc_hd__or3_2 _0592_ (
    .A(_0249_),
    .B(_0251_),
    .C(_0253_),
    .X(_0254_)
  );
  sky130_fd_sc_hd__o22ai_2 _0593_ (
    .A1(\DDATA[0][11] ),
    .A2(_0101_),
    .B1(_0247_),
    .B2(_0254_),
    .Y(_0255_)
  );
  sky130_fd_sc_hd__nor2_2 _0594_ (
    .A(_0135_),
    .B(_0255_),
    .Y(_0019_)
  );
  sky130_fd_sc_hd__a22o_2 _0595_ (
    .A1(\DDATA[7][12] ),
    .A2(_0116_),
    .B1(_0122_),
    .B2(\DDATA[13][12] ),
    .X(_0256_)
  );
  sky130_fd_sc_hd__a221o_2 _0596_ (
    .A1(\DDATA[5][12] ),
    .A2(_0114_),
    .B1(_0124_),
    .B2(\DDATA[15][12] ),
    .C1(_0256_),
    .X(_0257_)
  );
  sky130_fd_sc_hd__a22o_2 _0597_ (
    .A1(\DDATA[6][12] ),
    .A2(_0115_),
    .B1(_0121_),
    .B2(\DDATA[12][12] ),
    .X(_0258_)
  );
  sky130_fd_sc_hd__a221o_2 _0598_ (
    .A1(\DDATA[4][12] ),
    .A2(_0113_),
    .B1(_0123_),
    .B2(\DDATA[14][12] ),
    .C1(_0258_),
    .X(_0259_)
  );
  sky130_fd_sc_hd__a22o_2 _0599_ (
    .A1(\DDATA[2][12] ),
    .A2(_0111_),
    .B1(_0117_),
    .B2(\DDATA[8][12] ),
    .X(_0260_)
  );
  sky130_fd_sc_hd__a221o_2 _0600_ (
    .A1(\DDATA[3][12] ),
    .A2(_0112_),
    .B1(_0118_),
    .B2(\DDATA[9][12] ),
    .C1(_0260_),
    .X(_0261_)
  );
  sky130_fd_sc_hd__a22o_2 _0601_ (
    .A1(\DDATA[1][12] ),
    .A2(_0110_),
    .B1(_0119_),
    .B2(\DDATA[10][12] ),
    .X(_0262_)
  );
  sky130_fd_sc_hd__a211o_2 _0602_ (
    .A1(\DDATA[11][12] ),
    .A2(_0120_),
    .B1(_0262_),
    .C1(_0100_),
    .X(_0263_)
  );
  sky130_fd_sc_hd__or3_2 _0603_ (
    .A(_0259_),
    .B(_0261_),
    .C(_0263_),
    .X(_0264_)
  );
  sky130_fd_sc_hd__o22ai_2 _0604_ (
    .A1(\DDATA[0][12] ),
    .A2(_0101_),
    .B1(_0257_),
    .B2(_0264_),
    .Y(_0265_)
  );
  sky130_fd_sc_hd__nor2_2 _0605_ (
    .A(_0135_),
    .B(_0265_),
    .Y(_0020_)
  );
  sky130_fd_sc_hd__a22o_2 _0606_ (
    .A1(\DDATA[2][13] ),
    .A2(_0111_),
    .B1(_0115_),
    .B2(\DDATA[6][13] ),
    .X(_0266_)
  );
  sky130_fd_sc_hd__a221o_2 _0607_ (
    .A1(\DDATA[5][13] ),
    .A2(_0114_),
    .B1(_0122_),
    .B2(\DDATA[13][13] ),
    .C1(_0266_),
    .X(_0267_)
  );
  sky130_fd_sc_hd__a22o_2 _0608_ (
    .A1(\DDATA[4][13] ),
    .A2(_0113_),
    .B1(_0121_),
    .B2(\DDATA[12][13] ),
    .X(_0268_)
  );
  sky130_fd_sc_hd__a22o_2 _0609_ (
    .A1(\DDATA[9][13] ),
    .A2(_0118_),
    .B1(_0120_),
    .B2(\DDATA[11][13] ),
    .X(_0269_)
  );
  sky130_fd_sc_hd__a221o_2 _0610_ (
    .A1(\DDATA[8][13] ),
    .A2(_0117_),
    .B1(_0124_),
    .B2(\DDATA[15][13] ),
    .C1(_0100_),
    .X(_0270_)
  );
  sky130_fd_sc_hd__a211o_2 _0611_ (
    .A1(\DDATA[10][13] ),
    .A2(_0119_),
    .B1(_0269_),
    .C1(_0270_),
    .X(_0271_)
  );
  sky130_fd_sc_hd__a22o_2 _0612_ (
    .A1(\DDATA[3][13] ),
    .A2(_0112_),
    .B1(_0123_),
    .B2(\DDATA[14][13] ),
    .X(_0272_)
  );
  sky130_fd_sc_hd__a221o_2 _0613_ (
    .A1(\DDATA[1][13] ),
    .A2(_0110_),
    .B1(_0116_),
    .B2(\DDATA[7][13] ),
    .C1(_0272_),
    .X(_0273_)
  );
  sky130_fd_sc_hd__or3_2 _0614_ (
    .A(_0268_),
    .B(_0271_),
    .C(_0273_),
    .X(_0274_)
  );
  sky130_fd_sc_hd__o22ai_2 _0615_ (
    .A1(\DDATA[0][13] ),
    .A2(_0101_),
    .B1(_0267_),
    .B2(_0274_),
    .Y(_0275_)
  );
  sky130_fd_sc_hd__nor2_2 _0616_ (
    .A(_0135_),
    .B(_0275_),
    .Y(_0021_)
  );
  sky130_fd_sc_hd__a22o_2 _0617_ (
    .A1(\DDATA[5][14] ),
    .A2(_0114_),
    .B1(_0121_),
    .B2(\DDATA[12][14] ),
    .X(_0276_)
  );
  sky130_fd_sc_hd__a221o_2 _0618_ (
    .A1(\DDATA[6][14] ),
    .A2(_0115_),
    .B1(_0124_),
    .B2(\DDATA[15][14] ),
    .C1(_0276_),
    .X(_0277_)
  );
  sky130_fd_sc_hd__a22o_2 _0619_ (
    .A1(\DDATA[7][14] ),
    .A2(_0116_),
    .B1(_0122_),
    .B2(\DDATA[13][14] ),
    .X(_0278_)
  );
  sky130_fd_sc_hd__a221o_2 _0620_ (
    .A1(\DDATA[4][14] ),
    .A2(_0113_),
    .B1(_0123_),
    .B2(\DDATA[14][14] ),
    .C1(_0278_),
    .X(_0279_)
  );
  sky130_fd_sc_hd__a22o_2 _0621_ (
    .A1(\DDATA[3][14] ),
    .A2(_0112_),
    .B1(_0118_),
    .B2(\DDATA[9][14] ),
    .X(_0280_)
  );
  sky130_fd_sc_hd__a221o_2 _0622_ (
    .A1(\DDATA[1][14] ),
    .A2(_0110_),
    .B1(_0119_),
    .B2(\DDATA[10][14] ),
    .C1(_0280_),
    .X(_0281_)
  );
  sky130_fd_sc_hd__a22o_2 _0623_ (
    .A1(\DDATA[2][14] ),
    .A2(_0111_),
    .B1(_0117_),
    .B2(\DDATA[8][14] ),
    .X(_0282_)
  );
  sky130_fd_sc_hd__a211o_2 _0624_ (
    .A1(\DDATA[11][14] ),
    .A2(_0120_),
    .B1(_0282_),
    .C1(_0100_),
    .X(_0283_)
  );
  sky130_fd_sc_hd__or3_2 _0625_ (
    .A(_0279_),
    .B(_0281_),
    .C(_0283_),
    .X(_0284_)
  );
  sky130_fd_sc_hd__o22ai_2 _0626_ (
    .A1(\DDATA[0][14] ),
    .A2(_0101_),
    .B1(_0277_),
    .B2(_0284_),
    .Y(_0285_)
  );
  sky130_fd_sc_hd__nor2_2 _0627_ (
    .A(_0135_),
    .B(_0285_),
    .Y(_0022_)
  );
  sky130_fd_sc_hd__a22o_2 _0628_ (
    .A1(\DDATA[5][15] ),
    .A2(_0114_),
    .B1(_0115_),
    .B2(\DDATA[6][15] ),
    .X(_0286_)
  );
  sky130_fd_sc_hd__a221o_2 _0629_ (
    .A1(\DDATA[7][15] ),
    .A2(_0116_),
    .B1(_0123_),
    .B2(\DDATA[14][15] ),
    .C1(_0286_),
    .X(_0287_)
  );
  sky130_fd_sc_hd__a22o_2 _0630_ (
    .A1(\DDATA[12][15] ),
    .A2(_0121_),
    .B1(_0122_),
    .B2(\DDATA[13][15] ),
    .X(_0288_)
  );
  sky130_fd_sc_hd__a221o_2 _0631_ (
    .A1(\DDATA[4][15] ),
    .A2(_0113_),
    .B1(_0124_),
    .B2(\DDATA[15][15] ),
    .C1(_0288_),
    .X(_0289_)
  );
  sky130_fd_sc_hd__a22o_2 _0632_ (
    .A1(\DDATA[9][15] ),
    .A2(_0118_),
    .B1(_0119_),
    .B2(\DDATA[10][15] ),
    .X(_0290_)
  );
  sky130_fd_sc_hd__a221o_2 _0633_ (
    .A1(\DDATA[2][15] ),
    .A2(_0111_),
    .B1(_0117_),
    .B2(\DDATA[8][15] ),
    .C1(_0290_),
    .X(_0291_)
  );
  sky130_fd_sc_hd__a22o_2 _0634_ (
    .A1(\DDATA[1][15] ),
    .A2(_0110_),
    .B1(_0120_),
    .B2(\DDATA[11][15] ),
    .X(_0292_)
  );
  sky130_fd_sc_hd__a211o_2 _0635_ (
    .A1(\DDATA[3][15] ),
    .A2(_0112_),
    .B1(_0292_),
    .C1(_0100_),
    .X(_0293_)
  );
  sky130_fd_sc_hd__or3_2 _0636_ (
    .A(_0289_),
    .B(_0291_),
    .C(_0293_),
    .X(_0294_)
  );
  sky130_fd_sc_hd__o22ai_2 _0637_ (
    .A1(\DDATA[0][15] ),
    .A2(_0101_),
    .B1(_0287_),
    .B2(_0294_),
    .Y(_0295_)
  );
  sky130_fd_sc_hd__nor2_2 _0638_ (
    .A(_0135_),
    .B(_0295_),
    .Y(_0023_)
  );
  sky130_fd_sc_hd__nor2_2 _0639_ (
    .A(_0133_),
    .B(_0145_),
    .Y(_0038_)
  );
  sky130_fd_sc_hd__nor2_2 _0640_ (
    .A(_0133_),
    .B(_0155_),
    .Y(_0045_)
  );
  sky130_fd_sc_hd__nor2_2 _0641_ (
    .A(_0133_),
    .B(_0165_),
    .Y(_0046_)
  );
  sky130_fd_sc_hd__nor2_2 _0642_ (
    .A(_0133_),
    .B(_0175_),
    .Y(_0047_)
  );
  sky130_fd_sc_hd__nor2_2 _0643_ (
    .A(_0133_),
    .B(_0185_),
    .Y(_0048_)
  );
  sky130_fd_sc_hd__nor2_2 _0644_ (
    .A(_0133_),
    .B(_0195_),
    .Y(_0049_)
  );
  sky130_fd_sc_hd__nor2_2 _0645_ (
    .A(_0133_),
    .B(_0205_),
    .Y(_0050_)
  );
  sky130_fd_sc_hd__nor2_2 _0646_ (
    .A(_0133_),
    .B(_0215_),
    .Y(_0051_)
  );
  sky130_fd_sc_hd__nor2_2 _0647_ (
    .A(_0133_),
    .B(_0225_),
    .Y(_0052_)
  );
  sky130_fd_sc_hd__nor2_2 _0648_ (
    .A(_0133_),
    .B(_0235_),
    .Y(_0053_)
  );
  sky130_fd_sc_hd__nor2_2 _0649_ (
    .A(_0133_),
    .B(_0245_),
    .Y(_0039_)
  );
  sky130_fd_sc_hd__nor2_2 _0650_ (
    .A(_0133_),
    .B(_0255_),
    .Y(_0040_)
  );
  sky130_fd_sc_hd__nor2_2 _0651_ (
    .A(_0133_),
    .B(_0265_),
    .Y(_0041_)
  );
  sky130_fd_sc_hd__nor2_2 _0652_ (
    .A(_0133_),
    .B(_0275_),
    .Y(_0042_)
  );
  sky130_fd_sc_hd__nor2_2 _0653_ (
    .A(_0133_),
    .B(_0285_),
    .Y(_0043_)
  );
  sky130_fd_sc_hd__nor2_2 _0654_ (
    .A(_0133_),
    .B(_0295_),
    .Y(_0044_)
  );
  sky130_fd_sc_hd__mux2_1 _0655_ (
    .A0(wdata[0]),
    .A1(PRDATA[0]),
    .S(_0103_),
    .X(_0000_)
  );
  sky130_fd_sc_hd__mux2_1 _0656_ (
    .A0(wdata[1]),
    .A1(PRDATA[1]),
    .S(_0103_),
    .X(_0007_)
  );
  sky130_fd_sc_hd__mux2_1 _0657_ (
    .A0(wdata[2]),
    .A1(PRDATA[2]),
    .S(_0103_),
    .X(_0008_)
  );
  sky130_fd_sc_hd__mux2_1 _0658_ (
    .A0(wdata[3]),
    .A1(PRDATA[3]),
    .S(_0103_),
    .X(_0009_)
  );
  sky130_fd_sc_hd__mux2_1 _0659_ (
    .A0(wdata[4]),
    .A1(PRDATA[4]),
    .S(_0103_),
    .X(_0010_)
  );
  sky130_fd_sc_hd__mux2_1 _0660_ (
    .A0(wdata[5]),
    .A1(PRDATA[5]),
    .S(_0103_),
    .X(_0011_)
  );
  sky130_fd_sc_hd__mux2_1 _0661_ (
    .A0(wdata[6]),
    .A1(PRDATA[6]),
    .S(_0103_),
    .X(_0012_)
  );
  sky130_fd_sc_hd__mux2_1 _0662_ (
    .A0(wdata[7]),
    .A1(PRDATA[7]),
    .S(_0103_),
    .X(_0013_)
  );
  sky130_fd_sc_hd__mux2_1 _0663_ (
    .A0(wdata[8]),
    .A1(PRDATA[8]),
    .S(_0103_),
    .X(_0014_)
  );
  sky130_fd_sc_hd__mux2_1 _0664_ (
    .A0(wdata[9]),
    .A1(PRDATA[9]),
    .S(_0103_),
    .X(_0015_)
  );
  sky130_fd_sc_hd__mux2_1 _0665_ (
    .A0(wdata[10]),
    .A1(PRDATA[10]),
    .S(_0103_),
    .X(_0001_)
  );
  sky130_fd_sc_hd__mux2_1 _0666_ (
    .A0(wdata[11]),
    .A1(PRDATA[11]),
    .S(_0103_),
    .X(_0002_)
  );
  sky130_fd_sc_hd__mux2_1 _0667_ (
    .A0(wdata[12]),
    .A1(PRDATA[12]),
    .S(_0103_),
    .X(_0003_)
  );
  sky130_fd_sc_hd__mux2_1 _0668_ (
    .A0(wdata[13]),
    .A1(PRDATA[13]),
    .S(_0103_),
    .X(_0004_)
  );
  sky130_fd_sc_hd__mux2_1 _0669_ (
    .A0(wdata[14]),
    .A1(PRDATA[14]),
    .S(_0103_),
    .X(_0005_)
  );
  sky130_fd_sc_hd__mux2_1 _0670_ (
    .A0(wdata[15]),
    .A1(PRDATA[15]),
    .S(_0103_),
    .X(_0006_)
  );
  sky130_fd_sc_hd__mux2_1 _0671_ (
    .A0(awaddr[1]),
    .A1(araddr[1]),
    .S(arready),
    .X(_0033_)
  );
  sky130_fd_sc_hd__mux2_1 _0672_ (
    .A0(awaddr[3]),
    .A1(araddr[3]),
    .S(arready),
    .X(_0034_)
  );
  sky130_fd_sc_hd__mux2_1 _0673_ (
    .A0(awaddr[4]),
    .A1(araddr[4]),
    .S(arready),
    .X(_0035_)
  );
  sky130_fd_sc_hd__mux2_1 _0674_ (
    .A0(awburst[0]),
    .A1(arburst[0]),
    .S(arready),
    .X(_0036_)
  );
  sky130_fd_sc_hd__mux2_1 _0675_ (
    .A0(awburst[1]),
    .A1(arburst[1]),
    .S(arready),
    .X(_0037_)
  );
  sky130_fd_sc_hd__and4bb_2 _0676_ (
    .A_N(\current_state[0] ),
    .B_N(\current_state[3] ),
    .C(\current_state[2] ),
    .D(\current_state[1] ),
    .X(awready)
  );
  sky130_fd_sc_hd__or4_2 _0677_ (
    .A(\current_state[0] ),
    .B(\current_state[1] ),
    .C(\current_state[2] ),
    .D(\current_state[3] ),
    .X(_0296_)
  );
  sky130_fd_sc_hd__mux2_1 _0678_ (
    .A0(_0107_),
    .A1(_0296_),
    .S(_0133_),
    .X(_0054_)
  );
  sky130_fd_sc_hd__or2_2 _0679_ (
    .A(\lenS[0] ),
    .B(\lenS[1] ),
    .X(_0297_)
  );
  sky130_fd_sc_hd__or3_2 _0680_ (
    .A(\lenS[0] ),
    .B(\lenS[1] ),
    .C(\lenS[2] ),
    .X(_0298_)
  );
  sky130_fd_sc_hd__nor2_2 _0681_ (
    .A(\lenS[3] ),
    .B(_0298_),
    .Y(_0299_)
  );
  sky130_fd_sc_hd__or4_2 _0682_ (
    .A(\lenS[0] ),
    .B(\lenS[1] ),
    .C(\lenS[2] ),
    .D(\lenS[3] ),
    .X(_0300_)
  );
  sky130_fd_sc_hd__o31a_2 _0683_ (
    .A1(_0097_),
    .A2(_0135_),
    .A3(_0299_),
    .B1(_0296_),
    .X(_0055_)
  );
  sky130_fd_sc_hd__nand2_2 _0684_ (
    .A(bready),
    .B(bresp),
    .Y(_0301_)
  );
  sky130_fd_sc_hd__and2_2 _0685_ (
    .A(_0296_),
    .B(_0301_),
    .X(_0056_)
  );
  sky130_fd_sc_hd__nand2_2 _0686_ (
    .A(arvalid),
    .B(arready),
    .Y(_0302_)
  );
  sky130_fd_sc_hd__nand2_2 _0687_ (
    .A(awvalid),
    .B(awready),
    .Y(_0303_)
  );
  sky130_fd_sc_hd__and2_2 _0688_ (
    .A(_0302_),
    .B(_0303_),
    .X(_0057_)
  );
  sky130_fd_sc_hd__o31a_2 _0689_ (
    .A1(\lenM[1] ),
    .A2(\lenM[2] ),
    .A3(\lenM[3] ),
    .B1(rresp),
    .X(_0304_)
  );
  sky130_fd_sc_hd__or2_2 _0690_ (
    .A(_0054_),
    .B(_0304_),
    .X(_0058_)
  );
  sky130_fd_sc_hd__nand2_2 _0691_ (
    .A(bready),
    .B(\current_state[0] ),
    .Y(_0305_)
  );
  sky130_fd_sc_hd__and3_2 _0692_ (
    .A(_0098_),
    .B(_0126_),
    .C(_0305_),
    .X(_0306_)
  );
  sky130_fd_sc_hd__or3_2 _0693_ (
    .A(\current_state[0] ),
    .B(\current_state[1] ),
    .C(_0132_),
    .X(_0307_)
  );
  sky130_fd_sc_hd__nor2_2 _0694_ (
    .A(_0126_),
    .B(_0132_),
    .Y(_0308_)
  );
  sky130_fd_sc_hd__o22ai_2 _0695_ (
    .A1(_0094_),
    .A2(_0296_),
    .B1(_0307_),
    .B2(_0095_),
    .Y(_0309_)
  );
  sky130_fd_sc_hd__o311a_2 _0696_ (
    .A1(wvalid),
    .A2(_0126_),
    .A3(_0132_),
    .B1(_0303_),
    .C1(_0104_),
    .X(_0310_)
  );
  sky130_fd_sc_hd__or3b_2 _0697_ (
    .A(_0306_),
    .B(_0309_),
    .C_N(_0310_),
    .X(_0311_)
  );
  sky130_fd_sc_hd__a31o_2 _0698_ (
    .A1(PREADY),
    .A2(_0134_),
    .A3(_0299_),
    .B1(_0311_),
    .X(_0075_)
  );
  sky130_fd_sc_hd__or4_2 _0699_ (
    .A(wlast),
    .B(\current_state[0] ),
    .C(\current_state[1] ),
    .D(_0107_),
    .X(_0312_)
  );
  sky130_fd_sc_hd__or3_2 _0700_ (
    .A(arvalid),
    .B(_0096_),
    .C(_0296_),
    .X(_0313_)
  );
  sky130_fd_sc_hd__o311a_2 _0701_ (
    .A1(wvalid),
    .A2(_0126_),
    .A3(_0132_),
    .B1(_0303_),
    .C1(_0313_),
    .X(_0314_)
  );
  sky130_fd_sc_hd__o31ai_2 _0702_ (
    .A1(wlast),
    .A2(_0099_),
    .A3(_0107_),
    .B1(_0314_),
    .Y(_0315_)
  );
  sky130_fd_sc_hd__and3_2 _0703_ (
    .A(_0102_),
    .B(_0301_),
    .C(_0302_),
    .X(_0316_)
  );
  sky130_fd_sc_hd__and3b_2 _0704_ (
    .A_N(\current_state[3] ),
    .B(_0127_),
    .C(_0300_),
    .X(_0317_)
  );
  sky130_fd_sc_hd__or4b_2 _0705_ (
    .A(\lenS[1] ),
    .B(\lenS[2] ),
    .C(\lenS[3] ),
    .D_N(\lenS[0] ),
    .X(_0318_)
  );
  sky130_fd_sc_hd__and3_2 _0706_ (
    .A(PREADY),
    .B(_0134_),
    .C(_0318_),
    .X(_0319_)
  );
  sky130_fd_sc_hd__or4b_2 _0707_ (
    .A(_0315_),
    .B(_0317_),
    .C(_0319_),
    .D_N(_0316_),
    .X(_0076_)
  );
  sky130_fd_sc_hd__nor3_2 _0708_ (
    .A(\current_state[3] ),
    .B(_0128_),
    .C(_0300_),
    .Y(_0320_)
  );
  sky130_fd_sc_hd__or4b_2 _0709_ (
    .A(_0304_),
    .B(_0315_),
    .C(_0320_),
    .D_N(_0307_),
    .X(_0077_)
  );
  sky130_fd_sc_hd__a31o_2 _0710_ (
    .A1(_0098_),
    .A2(_0126_),
    .A3(_0312_),
    .B1(_0319_),
    .X(_0321_)
  );
  sky130_fd_sc_hd__a21o_2 _0711_ (
    .A1(wvalid),
    .A2(_0308_),
    .B1(_0321_),
    .X(_0078_)
  );
  sky130_fd_sc_hd__o2bb2a_2 _0712_ (
    .A1_N(awready),
    .A2_N(_0096_),
    .B1(arvalid),
    .B2(_0125_),
    .X(_0322_)
  );
  sky130_fd_sc_hd__nor2_2 _0713_ (
    .A(PREADY),
    .B(_0135_),
    .Y(_0323_)
  );
  sky130_fd_sc_hd__o32a_2 _0714_ (
    .A1(arready),
    .A2(_0127_),
    .A3(awready),
    .B1(_0135_),
    .B2(PREADY),
    .X(_0324_)
  );
  sky130_fd_sc_hd__o211a_2 _0715_ (
    .A1(_0128_),
    .A2(_0300_),
    .B1(_0322_),
    .C1(_0324_),
    .X(_0325_)
  );
  sky130_fd_sc_hd__o2bb2a_2 _0716_ (
    .A1_N(arlen[0]),
    .A2_N(arready),
    .B1(_0128_),
    .B2(\lenS[0] ),
    .X(_0326_)
  );
  sky130_fd_sc_hd__o21ai_2 _0717_ (
    .A1(awlen[0]),
    .A2(_0130_),
    .B1(_0326_),
    .Y(_0327_)
  );
  sky130_fd_sc_hd__mux2_1 _0718_ (
    .A0(\lenS[0] ),
    .A1(_0327_),
    .S(_0325_),
    .X(_0079_)
  );
  sky130_fd_sc_hd__xor2_2 _0719_ (
    .A(awlen[0]),
    .B(awlen[1]),
    .X(_0328_)
  );
  sky130_fd_sc_hd__nand2_2 _0720_ (
    .A(\lenS[0] ),
    .B(\lenS[1] ),
    .Y(_0329_)
  );
  sky130_fd_sc_hd__a21oi_2 _0721_ (
    .A1(_0297_),
    .A2(_0329_),
    .B1(_0128_),
    .Y(_0330_)
  );
  sky130_fd_sc_hd__a221o_2 _0722_ (
    .A1(arlen[1]),
    .A2(arready),
    .B1(_0129_),
    .B2(_0328_),
    .C1(_0330_),
    .X(_0331_)
  );
  sky130_fd_sc_hd__mux2_1 _0723_ (
    .A0(\lenS[1] ),
    .A1(_0331_),
    .S(_0325_),
    .X(_0080_)
  );
  sky130_fd_sc_hd__a21oi_2 _0724_ (
    .A1(awlen[0]),
    .A2(awlen[1]),
    .B1(awlen[2]),
    .Y(_0332_)
  );
  sky130_fd_sc_hd__and3_2 _0725_ (
    .A(awlen[0]),
    .B(awlen[1]),
    .C(awlen[2]),
    .X(_0333_)
  );
  sky130_fd_sc_hd__or2_2 _0726_ (
    .A(_0332_),
    .B(_0333_),
    .X(_0334_)
  );
  sky130_fd_sc_hd__inv_2 _0727_ (
    .A(_0334_),
    .Y(_0335_)
  );
  sky130_fd_sc_hd__nand2_2 _0728_ (
    .A(\lenS[2] ),
    .B(_0297_),
    .Y(_0336_)
  );
  sky130_fd_sc_hd__a21oi_2 _0729_ (
    .A1(_0298_),
    .A2(_0336_),
    .B1(_0128_),
    .Y(_0337_)
  );
  sky130_fd_sc_hd__a221o_2 _0730_ (
    .A1(arlen[2]),
    .A2(arready),
    .B1(_0129_),
    .B2(_0335_),
    .C1(_0337_),
    .X(_0338_)
  );
  sky130_fd_sc_hd__mux2_1 _0731_ (
    .A0(\lenS[2] ),
    .A1(_0338_),
    .S(_0325_),
    .X(_0081_)
  );
  sky130_fd_sc_hd__a21bo_2 _0732_ (
    .A1(_0127_),
    .A2(_0298_),
    .B1_N(_0325_),
    .X(_0339_)
  );
  sky130_fd_sc_hd__xnor2_2 _0733_ (
    .A(awlen[3]),
    .B(_0333_),
    .Y(_0340_)
  );
  sky130_fd_sc_hd__a2bb2o_2 _0734_ (
    .A1_N(_0130_),
    .A2_N(_0340_),
    .B1(arlen[3]),
    .B2(arready),
    .X(_0341_)
  );
  sky130_fd_sc_hd__a22o_2 _0735_ (
    .A1(\lenS[3] ),
    .A2(_0339_),
    .B1(_0341_),
    .B2(_0325_),
    .X(_0082_)
  );
  sky130_fd_sc_hd__nor2_2 _0736_ (
    .A(wready),
    .B(rresp),
    .Y(_0342_)
  );
  sky130_fd_sc_hd__or2_2 _0737_ (
    .A(wready),
    .B(rresp),
    .X(_0343_)
  );
  sky130_fd_sc_hd__nand2_2 _0738_ (
    .A(_0125_),
    .B(_0342_),
    .Y(_0344_)
  );
  sky130_fd_sc_hd__inv_2 _0739_ (
    .A(_0344_),
    .Y(_0345_)
  );
  sky130_fd_sc_hd__o221a_2 _0740_ (
    .A1(_0108_),
    .A2(_0342_),
    .B1(_0344_),
    .B2(awready),
    .C1(_0322_),
    .X(_0346_)
  );
  sky130_fd_sc_hd__a21bo_2 _0741_ (
    .A1(\lenM[0] ),
    .A2(_0343_),
    .B1_N(_0346_),
    .X(_0347_)
  );
  sky130_fd_sc_hd__o22a_2 _0742_ (
    .A1(arlen[0]),
    .A2(_0125_),
    .B1(_0342_),
    .B2(\lenM[0] ),
    .X(_0348_)
  );
  sky130_fd_sc_hd__o21ai_2 _0743_ (
    .A1(awlen[0]),
    .A2(_0344_),
    .B1(_0348_),
    .Y(_0349_)
  );
  sky130_fd_sc_hd__mux2_1 _0744_ (
    .A0(\lenM[0] ),
    .A1(_0349_),
    .S(_0346_),
    .X(_0083_)
  );
  sky130_fd_sc_hd__o21ai_2 _0745_ (
    .A1(_0105_),
    .A2(_0342_),
    .B1(_0346_),
    .Y(_0350_)
  );
  sky130_fd_sc_hd__o21ai_2 _0746_ (
    .A1(arlen[0]),
    .A2(arlen[1]),
    .B1(arready),
    .Y(_0351_)
  );
  sky130_fd_sc_hd__a21oi_2 _0747_ (
    .A1(arlen[0]),
    .A2(arlen[1]),
    .B1(_0351_),
    .Y(_0352_)
  );
  sky130_fd_sc_hd__a221o_2 _0748_ (
    .A1(_0105_),
    .A2(_0343_),
    .B1(_0345_),
    .B2(_0328_),
    .C1(_0352_),
    .X(_0353_)
  );
  sky130_fd_sc_hd__a22o_2 _0749_ (
    .A1(\lenM[1] ),
    .A2(_0347_),
    .B1(_0353_),
    .B2(_0346_),
    .X(_0084_)
  );
  sky130_fd_sc_hd__and3_2 _0750_ (
    .A(arlen[0]),
    .B(arlen[1]),
    .C(arlen[2]),
    .X(_0354_)
  );
  sky130_fd_sc_hd__a21oi_2 _0751_ (
    .A1(arlen[0]),
    .A2(arlen[1]),
    .B1(arlen[2]),
    .Y(_0355_)
  );
  sky130_fd_sc_hd__o32a_2 _0752_ (
    .A1(_0125_),
    .A2(_0354_),
    .A3(_0355_),
    .B1(_0334_),
    .B2(_0344_),
    .X(_0356_)
  );
  sky130_fd_sc_hd__o21ai_2 _0753_ (
    .A1(_0106_),
    .A2(_0342_),
    .B1(_0356_),
    .Y(_0357_)
  );
  sky130_fd_sc_hd__a22o_2 _0754_ (
    .A1(\lenM[2] ),
    .A2(_0350_),
    .B1(_0357_),
    .B2(_0346_),
    .X(_0085_)
  );
  sky130_fd_sc_hd__a21bo_2 _0755_ (
    .A1(_0106_),
    .A2(_0343_),
    .B1_N(_0346_),
    .X(_0358_)
  );
  sky130_fd_sc_hd__nand2_2 _0756_ (
    .A(arlen[3]),
    .B(_0354_),
    .Y(_0359_)
  );
  sky130_fd_sc_hd__o21a_2 _0757_ (
    .A1(arlen[3]),
    .A2(_0354_),
    .B1(arready),
    .X(_0360_)
  );
  sky130_fd_sc_hd__a2bb2o_2 _0758_ (
    .A1_N(_0340_),
    .A2_N(_0344_),
    .B1(_0359_),
    .B2(_0360_),
    .X(_0361_)
  );
  sky130_fd_sc_hd__a22o_2 _0759_ (
    .A1(\lenM[3] ),
    .A2(_0358_),
    .B1(_0361_),
    .B2(_0346_),
    .X(_0086_)
  );
  sky130_fd_sc_hd__and2b_2 _0760_ (
    .A_N(\burst[1] ),
    .B(\burst[0] ),
    .X(_0362_)
  );
  sky130_fd_sc_hd__o41a_2 _0761_ (
    .A1(\current_state[3] ),
    .A2(_0128_),
    .A3(_0299_),
    .A4(_0362_),
    .B1(_0325_),
    .X(_0363_)
  );
  sky130_fd_sc_hd__nor2_2 _0762_ (
    .A(\DADDR[0] ),
    .B(_0128_),
    .Y(_0364_)
  );
  sky130_fd_sc_hd__a221o_2 _0763_ (
    .A1(araddr[0]),
    .A2(arready),
    .B1(_0129_),
    .B2(awaddr[0]),
    .C1(_0364_),
    .X(_0365_)
  );
  sky130_fd_sc_hd__mux2_1 _0764_ (
    .A0(\DADDR[0] ),
    .A1(_0365_),
    .S(_0363_),
    .X(_0087_)
  );
  sky130_fd_sc_hd__a21o_2 _0765_ (
    .A1(\DADDR[0] ),
    .A2(\DADDR[1] ),
    .B1(_0128_),
    .X(_0366_)
  );
  sky130_fd_sc_hd__nand2_2 _0766_ (
    .A(_0363_),
    .B(_0366_),
    .Y(_0367_)
  );
  sky130_fd_sc_hd__o2bb2a_2 _0767_ (
    .A1_N(_0363_),
    .A2_N(_0366_),
    .B1(\DADDR[0] ),
    .B2(\DADDR[1] ),
    .X(_0368_)
  );
  sky130_fd_sc_hd__and2_2 _0768_ (
    .A(_0128_),
    .B(_0033_),
    .X(_0369_)
  );
  sky130_fd_sc_hd__o22a_2 _0769_ (
    .A1(\DADDR[1] ),
    .A2(_0363_),
    .B1(_0368_),
    .B2(_0369_),
    .X(_0088_)
  );
  sky130_fd_sc_hd__and4b_2 _0770_ (
    .A_N(\DADDR[2] ),
    .B(_0127_),
    .C(\DADDR[0] ),
    .D(\DADDR[1] ),
    .X(_0370_)
  );
  sky130_fd_sc_hd__a221o_2 _0771_ (
    .A1(araddr[2]),
    .A2(arready),
    .B1(_0129_),
    .B2(awaddr[2]),
    .C1(_0370_),
    .X(_0371_)
  );
  sky130_fd_sc_hd__a22o_2 _0772_ (
    .A1(\DADDR[2] ),
    .A2(_0367_),
    .B1(_0371_),
    .B2(_0363_),
    .X(_0089_)
  );
  sky130_fd_sc_hd__a32o_2 _0773_ (
    .A1(PREADY),
    .A2(_0134_),
    .A3(_0299_),
    .B1(_0107_),
    .B2(rresp),
    .X(_0372_)
  );
  sky130_fd_sc_hd__a31o_2 _0774_ (
    .A1(_0128_),
    .A2(_0296_),
    .A3(_0342_),
    .B1(_0320_),
    .X(_0373_)
  );
  sky130_fd_sc_hd__a21oi_2 _0775_ (
    .A1(_0108_),
    .A2(_0362_),
    .B1(_0099_),
    .Y(_0374_)
  );
  sky130_fd_sc_hd__or4_2 _0776_ (
    .A(_0323_),
    .B(_0372_),
    .C(_0373_),
    .D(_0374_),
    .X(_0375_)
  );
  sky130_fd_sc_hd__and2b_2 _0777_ (
    .A_N(_0375_),
    .B(_0296_),
    .X(_0376_)
  );
  sky130_fd_sc_hd__mux2_1 _0778_ (
    .A0(_0376_),
    .A1(_0375_),
    .S(\i[0] ),
    .X(_0090_)
  );
  sky130_fd_sc_hd__nand2_2 _0779_ (
    .A(_0133_),
    .B(_0135_),
    .Y(_0377_)
  );
  sky130_fd_sc_hd__o21a_2 _0780_ (
    .A1(rresp),
    .A2(_0134_),
    .B1(\i[1] ),
    .X(_0378_)
  );
  sky130_fd_sc_hd__or3_2 _0781_ (
    .A(\i[1] ),
    .B(rresp),
    .C(_0134_),
    .X(_0379_)
  );
  sky130_fd_sc_hd__nand2b_2 _0782_ (
    .A_N(_0378_),
    .B(_0379_),
    .Y(_0380_)
  );
  sky130_fd_sc_hd__xnor2_2 _0783_ (
    .A(\i[0] ),
    .B(_0380_),
    .Y(_0381_)
  );
  sky130_fd_sc_hd__a22o_2 _0784_ (
    .A1(\i[1] ),
    .A2(_0375_),
    .B1(_0376_),
    .B2(_0381_),
    .X(_0091_)
  );
  sky130_fd_sc_hd__a21o_2 _0785_ (
    .A1(\i[0] ),
    .A2(_0379_),
    .B1(_0378_),
    .X(_0382_)
  );
  sky130_fd_sc_hd__nand2_2 _0786_ (
    .A(\i[2] ),
    .B(_0377_),
    .Y(_0383_)
  );
  sky130_fd_sc_hd__or2_2 _0787_ (
    .A(\i[2] ),
    .B(_0377_),
    .X(_0384_)
  );
  sky130_fd_sc_hd__nand2_2 _0788_ (
    .A(_0383_),
    .B(_0384_),
    .Y(_0385_)
  );
  sky130_fd_sc_hd__xnor2_2 _0789_ (
    .A(_0382_),
    .B(_0385_),
    .Y(_0386_)
  );
  sky130_fd_sc_hd__a22o_2 _0790_ (
    .A1(\i[2] ),
    .A2(_0375_),
    .B1(_0376_),
    .B2(_0386_),
    .X(_0092_)
  );
  sky130_fd_sc_hd__a21bo_2 _0791_ (
    .A1(_0382_),
    .A2(_0384_),
    .B1_N(_0383_),
    .X(_0387_)
  );
  sky130_fd_sc_hd__xnor2_2 _0792_ (
    .A(\i[3] ),
    .B(_0377_),
    .Y(_0388_)
  );
  sky130_fd_sc_hd__xnor2_2 _0793_ (
    .A(_0387_),
    .B(_0388_),
    .Y(_0389_)
  );
  sky130_fd_sc_hd__a22o_2 _0794_ (
    .A1(\i[3] ),
    .A2(_0375_),
    .B1(_0376_),
    .B2(_0389_),
    .X(_0093_)
  );
  sky130_fd_sc_hd__dfrtp_2 _0795_ (
    .CLK(clk),
    .D(_0075_),
    .Q(\current_state[0] ),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _0796_ (
    .CLK(clk),
    .D(_0076_),
    .Q(\current_state[1] ),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _0797_ (
    .CLK(clk),
    .D(_0077_),
    .Q(\current_state[2] ),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _0798_ (
    .CLK(clk),
    .D(_0078_),
    .Q(\current_state[3] ),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _0799_ (
    .CLK(clk),
    .D(_0079_),
    .Q(\lenS[0] ),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _0800_ (
    .CLK(clk),
    .D(_0080_),
    .Q(\lenS[1] ),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _0801_ (
    .CLK(clk),
    .D(_0081_),
    .Q(\lenS[2] ),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _0802_ (
    .CLK(clk),
    .D(_0082_),
    .Q(\lenS[3] ),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dlxtn_1 _0803_ (
    .D(_0038_),
    .GATE_N(_0054_),
    .Q(rdata[0])
  );
  sky130_fd_sc_hd__dlxtn_1 _0804_ (
    .D(_0045_),
    .GATE_N(_0054_),
    .Q(rdata[1])
  );
  sky130_fd_sc_hd__dlxtn_1 _0805_ (
    .D(_0046_),
    .GATE_N(_0054_),
    .Q(rdata[2])
  );
  sky130_fd_sc_hd__dlxtn_1 _0806_ (
    .D(_0047_),
    .GATE_N(_0054_),
    .Q(rdata[3])
  );
  sky130_fd_sc_hd__dlxtn_1 _0807_ (
    .D(_0048_),
    .GATE_N(_0054_),
    .Q(rdata[4])
  );
  sky130_fd_sc_hd__dlxtn_1 _0808_ (
    .D(_0049_),
    .GATE_N(_0054_),
    .Q(rdata[5])
  );
  sky130_fd_sc_hd__dlxtn_1 _0809_ (
    .D(_0050_),
    .GATE_N(_0054_),
    .Q(rdata[6])
  );
  sky130_fd_sc_hd__dlxtn_1 _0810_ (
    .D(_0051_),
    .GATE_N(_0054_),
    .Q(rdata[7])
  );
  sky130_fd_sc_hd__dlxtn_1 _0811_ (
    .D(_0052_),
    .GATE_N(_0054_),
    .Q(rdata[8])
  );
  sky130_fd_sc_hd__dlxtn_1 _0812_ (
    .D(_0053_),
    .GATE_N(_0054_),
    .Q(rdata[9])
  );
  sky130_fd_sc_hd__dlxtn_1 _0813_ (
    .D(_0039_),
    .GATE_N(_0054_),
    .Q(rdata[10])
  );
  sky130_fd_sc_hd__dlxtn_1 _0814_ (
    .D(_0040_),
    .GATE_N(_0054_),
    .Q(rdata[11])
  );
  sky130_fd_sc_hd__dlxtn_1 _0815_ (
    .D(_0041_),
    .GATE_N(_0054_),
    .Q(rdata[12])
  );
  sky130_fd_sc_hd__dlxtn_1 _0816_ (
    .D(_0042_),
    .GATE_N(_0054_),
    .Q(rdata[13])
  );
  sky130_fd_sc_hd__dlxtn_1 _0817_ (
    .D(_0043_),
    .GATE_N(_0054_),
    .Q(rdata[14])
  );
  sky130_fd_sc_hd__dlxtn_1 _0818_ (
    .D(_0044_),
    .GATE_N(_0054_),
    .Q(rdata[15])
  );
  sky130_fd_sc_hd__dlxtn_1 _0819_ (
    .D(_0017_),
    .GATE_N(_0055_),
    .Q(PWDATA[0])
  );
  sky130_fd_sc_hd__dlxtn_1 _0820_ (
    .D(_0024_),
    .GATE_N(_0055_),
    .Q(PWDATA[1])
  );
  sky130_fd_sc_hd__dlxtn_1 _0821_ (
    .D(_0025_),
    .GATE_N(_0055_),
    .Q(PWDATA[2])
  );
  sky130_fd_sc_hd__dlxtn_1 _0822_ (
    .D(_0026_),
    .GATE_N(_0055_),
    .Q(PWDATA[3])
  );
  sky130_fd_sc_hd__dlxtn_1 _0823_ (
    .D(_0027_),
    .GATE_N(_0055_),
    .Q(PWDATA[4])
  );
  sky130_fd_sc_hd__dlxtn_1 _0824_ (
    .D(_0028_),
    .GATE_N(_0055_),
    .Q(PWDATA[5])
  );
  sky130_fd_sc_hd__dlxtn_1 _0825_ (
    .D(_0029_),
    .GATE_N(_0055_),
    .Q(PWDATA[6])
  );
  sky130_fd_sc_hd__dlxtn_1 _0826_ (
    .D(_0030_),
    .GATE_N(_0055_),
    .Q(PWDATA[7])
  );
  sky130_fd_sc_hd__dlxtn_1 _0827_ (
    .D(_0031_),
    .GATE_N(_0055_),
    .Q(PWDATA[8])
  );
  sky130_fd_sc_hd__dlxtn_1 _0828_ (
    .D(_0032_),
    .GATE_N(_0055_),
    .Q(PWDATA[9])
  );
  sky130_fd_sc_hd__dlxtn_1 _0829_ (
    .D(_0018_),
    .GATE_N(_0055_),
    .Q(PWDATA[10])
  );
  sky130_fd_sc_hd__dlxtn_1 _0830_ (
    .D(_0019_),
    .GATE_N(_0055_),
    .Q(PWDATA[11])
  );
  sky130_fd_sc_hd__dlxtn_1 _0831_ (
    .D(_0020_),
    .GATE_N(_0055_),
    .Q(PWDATA[12])
  );
  sky130_fd_sc_hd__dlxtn_1 _0832_ (
    .D(_0021_),
    .GATE_N(_0055_),
    .Q(PWDATA[13])
  );
  sky130_fd_sc_hd__dlxtn_1 _0833_ (
    .D(_0022_),
    .GATE_N(_0055_),
    .Q(PWDATA[14])
  );
  sky130_fd_sc_hd__dlxtn_1 _0834_ (
    .D(_0023_),
    .GATE_N(_0055_),
    .Q(PWDATA[15])
  );
  sky130_fd_sc_hd__dlxtn_1 _0835_ (
    .D(_0016_),
    .GATE_N(_0056_),
    .Q(\DWREQ[0] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0836_ (
    .D(bresp),
    .GATE_N(_0056_),
    .Q(\DWREQ[1] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0837_ (
    .D(_0036_),
    .GATE_N(_0057_),
    .Q(\burst[0] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0838_ (
    .D(_0037_),
    .GATE_N(_0057_),
    .Q(\burst[1] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0839_ (
    .D(_0034_),
    .GATE_N(_0057_),
    .Q(\addr[3] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0840_ (
    .D(_0035_),
    .GATE_N(_0057_),
    .Q(\addr[4] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0841_ (
    .D(rresp),
    .GATE_N(_0058_),
    .Q(last)
  );
  sky130_fd_sc_hd__dlxtn_1 _0842_ (
    .D(_0000_),
    .GATE_N(_0059_),
    .Q(\DDATA[0][0] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0843_ (
    .D(_0007_),
    .GATE_N(_0059_),
    .Q(\DDATA[0][1] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0844_ (
    .D(_0008_),
    .GATE_N(_0059_),
    .Q(\DDATA[0][2] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0845_ (
    .D(_0009_),
    .GATE_N(_0059_),
    .Q(\DDATA[0][3] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0846_ (
    .D(_0010_),
    .GATE_N(_0059_),
    .Q(\DDATA[0][4] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0847_ (
    .D(_0011_),
    .GATE_N(_0059_),
    .Q(\DDATA[0][5] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0848_ (
    .D(_0012_),
    .GATE_N(_0059_),
    .Q(\DDATA[0][6] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0849_ (
    .D(_0013_),
    .GATE_N(_0059_),
    .Q(\DDATA[0][7] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0850_ (
    .D(_0014_),
    .GATE_N(_0059_),
    .Q(\DDATA[0][8] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0851_ (
    .D(_0015_),
    .GATE_N(_0059_),
    .Q(\DDATA[0][9] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0852_ (
    .D(_0001_),
    .GATE_N(_0059_),
    .Q(\DDATA[0][10] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0853_ (
    .D(_0002_),
    .GATE_N(_0059_),
    .Q(\DDATA[0][11] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0854_ (
    .D(_0003_),
    .GATE_N(_0059_),
    .Q(\DDATA[0][12] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0855_ (
    .D(_0004_),
    .GATE_N(_0059_),
    .Q(\DDATA[0][13] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0856_ (
    .D(_0005_),
    .GATE_N(_0059_),
    .Q(\DDATA[0][14] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0857_ (
    .D(_0006_),
    .GATE_N(_0059_),
    .Q(\DDATA[0][15] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0858_ (
    .D(_0000_),
    .GATE_N(_0060_),
    .Q(\DDATA[1][0] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0859_ (
    .D(_0007_),
    .GATE_N(_0060_),
    .Q(\DDATA[1][1] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0860_ (
    .D(_0008_),
    .GATE_N(_0060_),
    .Q(\DDATA[1][2] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0861_ (
    .D(_0009_),
    .GATE_N(_0060_),
    .Q(\DDATA[1][3] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0862_ (
    .D(_0010_),
    .GATE_N(_0060_),
    .Q(\DDATA[1][4] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0863_ (
    .D(_0011_),
    .GATE_N(_0060_),
    .Q(\DDATA[1][5] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0864_ (
    .D(_0012_),
    .GATE_N(_0060_),
    .Q(\DDATA[1][6] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0865_ (
    .D(_0013_),
    .GATE_N(_0060_),
    .Q(\DDATA[1][7] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0866_ (
    .D(_0014_),
    .GATE_N(_0060_),
    .Q(\DDATA[1][8] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0867_ (
    .D(_0015_),
    .GATE_N(_0060_),
    .Q(\DDATA[1][9] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0868_ (
    .D(_0001_),
    .GATE_N(_0060_),
    .Q(\DDATA[1][10] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0869_ (
    .D(_0002_),
    .GATE_N(_0060_),
    .Q(\DDATA[1][11] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0870_ (
    .D(_0003_),
    .GATE_N(_0060_),
    .Q(\DDATA[1][12] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0871_ (
    .D(_0004_),
    .GATE_N(_0060_),
    .Q(\DDATA[1][13] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0872_ (
    .D(_0005_),
    .GATE_N(_0060_),
    .Q(\DDATA[1][14] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0873_ (
    .D(_0006_),
    .GATE_N(_0060_),
    .Q(\DDATA[1][15] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0874_ (
    .D(_0000_),
    .GATE_N(_0061_),
    .Q(\DDATA[2][0] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0875_ (
    .D(_0007_),
    .GATE_N(_0061_),
    .Q(\DDATA[2][1] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0876_ (
    .D(_0008_),
    .GATE_N(_0061_),
    .Q(\DDATA[2][2] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0877_ (
    .D(_0009_),
    .GATE_N(_0061_),
    .Q(\DDATA[2][3] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0878_ (
    .D(_0010_),
    .GATE_N(_0061_),
    .Q(\DDATA[2][4] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0879_ (
    .D(_0011_),
    .GATE_N(_0061_),
    .Q(\DDATA[2][5] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0880_ (
    .D(_0012_),
    .GATE_N(_0061_),
    .Q(\DDATA[2][6] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0881_ (
    .D(_0013_),
    .GATE_N(_0061_),
    .Q(\DDATA[2][7] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0882_ (
    .D(_0014_),
    .GATE_N(_0061_),
    .Q(\DDATA[2][8] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0883_ (
    .D(_0015_),
    .GATE_N(_0061_),
    .Q(\DDATA[2][9] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0884_ (
    .D(_0001_),
    .GATE_N(_0061_),
    .Q(\DDATA[2][10] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0885_ (
    .D(_0002_),
    .GATE_N(_0061_),
    .Q(\DDATA[2][11] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0886_ (
    .D(_0003_),
    .GATE_N(_0061_),
    .Q(\DDATA[2][12] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0887_ (
    .D(_0004_),
    .GATE_N(_0061_),
    .Q(\DDATA[2][13] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0888_ (
    .D(_0005_),
    .GATE_N(_0061_),
    .Q(\DDATA[2][14] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0889_ (
    .D(_0006_),
    .GATE_N(_0061_),
    .Q(\DDATA[2][15] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0890_ (
    .D(_0000_),
    .GATE_N(_0062_),
    .Q(\DDATA[3][0] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0891_ (
    .D(_0007_),
    .GATE_N(_0062_),
    .Q(\DDATA[3][1] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0892_ (
    .D(_0008_),
    .GATE_N(_0062_),
    .Q(\DDATA[3][2] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0893_ (
    .D(_0009_),
    .GATE_N(_0062_),
    .Q(\DDATA[3][3] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0894_ (
    .D(_0010_),
    .GATE_N(_0062_),
    .Q(\DDATA[3][4] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0895_ (
    .D(_0011_),
    .GATE_N(_0062_),
    .Q(\DDATA[3][5] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0896_ (
    .D(_0012_),
    .GATE_N(_0062_),
    .Q(\DDATA[3][6] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0897_ (
    .D(_0013_),
    .GATE_N(_0062_),
    .Q(\DDATA[3][7] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0898_ (
    .D(_0014_),
    .GATE_N(_0062_),
    .Q(\DDATA[3][8] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0899_ (
    .D(_0015_),
    .GATE_N(_0062_),
    .Q(\DDATA[3][9] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0900_ (
    .D(_0001_),
    .GATE_N(_0062_),
    .Q(\DDATA[3][10] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0901_ (
    .D(_0002_),
    .GATE_N(_0062_),
    .Q(\DDATA[3][11] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0902_ (
    .D(_0003_),
    .GATE_N(_0062_),
    .Q(\DDATA[3][12] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0903_ (
    .D(_0004_),
    .GATE_N(_0062_),
    .Q(\DDATA[3][13] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0904_ (
    .D(_0005_),
    .GATE_N(_0062_),
    .Q(\DDATA[3][14] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0905_ (
    .D(_0006_),
    .GATE_N(_0062_),
    .Q(\DDATA[3][15] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0906_ (
    .D(_0000_),
    .GATE_N(_0063_),
    .Q(\DDATA[4][0] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0907_ (
    .D(_0007_),
    .GATE_N(_0063_),
    .Q(\DDATA[4][1] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0908_ (
    .D(_0008_),
    .GATE_N(_0063_),
    .Q(\DDATA[4][2] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0909_ (
    .D(_0009_),
    .GATE_N(_0063_),
    .Q(\DDATA[4][3] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0910_ (
    .D(_0010_),
    .GATE_N(_0063_),
    .Q(\DDATA[4][4] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0911_ (
    .D(_0011_),
    .GATE_N(_0063_),
    .Q(\DDATA[4][5] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0912_ (
    .D(_0012_),
    .GATE_N(_0063_),
    .Q(\DDATA[4][6] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0913_ (
    .D(_0013_),
    .GATE_N(_0063_),
    .Q(\DDATA[4][7] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0914_ (
    .D(_0014_),
    .GATE_N(_0063_),
    .Q(\DDATA[4][8] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0915_ (
    .D(_0015_),
    .GATE_N(_0063_),
    .Q(\DDATA[4][9] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0916_ (
    .D(_0001_),
    .GATE_N(_0063_),
    .Q(\DDATA[4][10] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0917_ (
    .D(_0002_),
    .GATE_N(_0063_),
    .Q(\DDATA[4][11] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0918_ (
    .D(_0003_),
    .GATE_N(_0063_),
    .Q(\DDATA[4][12] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0919_ (
    .D(_0004_),
    .GATE_N(_0063_),
    .Q(\DDATA[4][13] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0920_ (
    .D(_0005_),
    .GATE_N(_0063_),
    .Q(\DDATA[4][14] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0921_ (
    .D(_0006_),
    .GATE_N(_0063_),
    .Q(\DDATA[4][15] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0922_ (
    .D(_0000_),
    .GATE_N(_0064_),
    .Q(\DDATA[5][0] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0923_ (
    .D(_0007_),
    .GATE_N(_0064_),
    .Q(\DDATA[5][1] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0924_ (
    .D(_0008_),
    .GATE_N(_0064_),
    .Q(\DDATA[5][2] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0925_ (
    .D(_0009_),
    .GATE_N(_0064_),
    .Q(\DDATA[5][3] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0926_ (
    .D(_0010_),
    .GATE_N(_0064_),
    .Q(\DDATA[5][4] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0927_ (
    .D(_0011_),
    .GATE_N(_0064_),
    .Q(\DDATA[5][5] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0928_ (
    .D(_0012_),
    .GATE_N(_0064_),
    .Q(\DDATA[5][6] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0929_ (
    .D(_0013_),
    .GATE_N(_0064_),
    .Q(\DDATA[5][7] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0930_ (
    .D(_0014_),
    .GATE_N(_0064_),
    .Q(\DDATA[5][8] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0931_ (
    .D(_0015_),
    .GATE_N(_0064_),
    .Q(\DDATA[5][9] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0932_ (
    .D(_0001_),
    .GATE_N(_0064_),
    .Q(\DDATA[5][10] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0933_ (
    .D(_0002_),
    .GATE_N(_0064_),
    .Q(\DDATA[5][11] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0934_ (
    .D(_0003_),
    .GATE_N(_0064_),
    .Q(\DDATA[5][12] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0935_ (
    .D(_0004_),
    .GATE_N(_0064_),
    .Q(\DDATA[5][13] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0936_ (
    .D(_0005_),
    .GATE_N(_0064_),
    .Q(\DDATA[5][14] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0937_ (
    .D(_0006_),
    .GATE_N(_0064_),
    .Q(\DDATA[5][15] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0938_ (
    .D(_0000_),
    .GATE_N(_0065_),
    .Q(\DDATA[6][0] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0939_ (
    .D(_0007_),
    .GATE_N(_0065_),
    .Q(\DDATA[6][1] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0940_ (
    .D(_0008_),
    .GATE_N(_0065_),
    .Q(\DDATA[6][2] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0941_ (
    .D(_0009_),
    .GATE_N(_0065_),
    .Q(\DDATA[6][3] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0942_ (
    .D(_0010_),
    .GATE_N(_0065_),
    .Q(\DDATA[6][4] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0943_ (
    .D(_0011_),
    .GATE_N(_0065_),
    .Q(\DDATA[6][5] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0944_ (
    .D(_0012_),
    .GATE_N(_0065_),
    .Q(\DDATA[6][6] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0945_ (
    .D(_0013_),
    .GATE_N(_0065_),
    .Q(\DDATA[6][7] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0946_ (
    .D(_0014_),
    .GATE_N(_0065_),
    .Q(\DDATA[6][8] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0947_ (
    .D(_0015_),
    .GATE_N(_0065_),
    .Q(\DDATA[6][9] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0948_ (
    .D(_0001_),
    .GATE_N(_0065_),
    .Q(\DDATA[6][10] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0949_ (
    .D(_0002_),
    .GATE_N(_0065_),
    .Q(\DDATA[6][11] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0950_ (
    .D(_0003_),
    .GATE_N(_0065_),
    .Q(\DDATA[6][12] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0951_ (
    .D(_0004_),
    .GATE_N(_0065_),
    .Q(\DDATA[6][13] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0952_ (
    .D(_0005_),
    .GATE_N(_0065_),
    .Q(\DDATA[6][14] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0953_ (
    .D(_0006_),
    .GATE_N(_0065_),
    .Q(\DDATA[6][15] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0954_ (
    .D(_0000_),
    .GATE_N(_0066_),
    .Q(\DDATA[7][0] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0955_ (
    .D(_0007_),
    .GATE_N(_0066_),
    .Q(\DDATA[7][1] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0956_ (
    .D(_0008_),
    .GATE_N(_0066_),
    .Q(\DDATA[7][2] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0957_ (
    .D(_0009_),
    .GATE_N(_0066_),
    .Q(\DDATA[7][3] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0958_ (
    .D(_0010_),
    .GATE_N(_0066_),
    .Q(\DDATA[7][4] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0959_ (
    .D(_0011_),
    .GATE_N(_0066_),
    .Q(\DDATA[7][5] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0960_ (
    .D(_0012_),
    .GATE_N(_0066_),
    .Q(\DDATA[7][6] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0961_ (
    .D(_0013_),
    .GATE_N(_0066_),
    .Q(\DDATA[7][7] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0962_ (
    .D(_0014_),
    .GATE_N(_0066_),
    .Q(\DDATA[7][8] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0963_ (
    .D(_0015_),
    .GATE_N(_0066_),
    .Q(\DDATA[7][9] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0964_ (
    .D(_0001_),
    .GATE_N(_0066_),
    .Q(\DDATA[7][10] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0965_ (
    .D(_0002_),
    .GATE_N(_0066_),
    .Q(\DDATA[7][11] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0966_ (
    .D(_0003_),
    .GATE_N(_0066_),
    .Q(\DDATA[7][12] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0967_ (
    .D(_0004_),
    .GATE_N(_0066_),
    .Q(\DDATA[7][13] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0968_ (
    .D(_0005_),
    .GATE_N(_0066_),
    .Q(\DDATA[7][14] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0969_ (
    .D(_0006_),
    .GATE_N(_0066_),
    .Q(\DDATA[7][15] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0970_ (
    .D(_0000_),
    .GATE_N(_0067_),
    .Q(\DDATA[8][0] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0971_ (
    .D(_0007_),
    .GATE_N(_0067_),
    .Q(\DDATA[8][1] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0972_ (
    .D(_0008_),
    .GATE_N(_0067_),
    .Q(\DDATA[8][2] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0973_ (
    .D(_0009_),
    .GATE_N(_0067_),
    .Q(\DDATA[8][3] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0974_ (
    .D(_0010_),
    .GATE_N(_0067_),
    .Q(\DDATA[8][4] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0975_ (
    .D(_0011_),
    .GATE_N(_0067_),
    .Q(\DDATA[8][5] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0976_ (
    .D(_0012_),
    .GATE_N(_0067_),
    .Q(\DDATA[8][6] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0977_ (
    .D(_0013_),
    .GATE_N(_0067_),
    .Q(\DDATA[8][7] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0978_ (
    .D(_0014_),
    .GATE_N(_0067_),
    .Q(\DDATA[8][8] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0979_ (
    .D(_0015_),
    .GATE_N(_0067_),
    .Q(\DDATA[8][9] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0980_ (
    .D(_0001_),
    .GATE_N(_0067_),
    .Q(\DDATA[8][10] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0981_ (
    .D(_0002_),
    .GATE_N(_0067_),
    .Q(\DDATA[8][11] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0982_ (
    .D(_0003_),
    .GATE_N(_0067_),
    .Q(\DDATA[8][12] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0983_ (
    .D(_0004_),
    .GATE_N(_0067_),
    .Q(\DDATA[8][13] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0984_ (
    .D(_0005_),
    .GATE_N(_0067_),
    .Q(\DDATA[8][14] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0985_ (
    .D(_0006_),
    .GATE_N(_0067_),
    .Q(\DDATA[8][15] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0986_ (
    .D(_0000_),
    .GATE_N(_0068_),
    .Q(\DDATA[9][0] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0987_ (
    .D(_0007_),
    .GATE_N(_0068_),
    .Q(\DDATA[9][1] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0988_ (
    .D(_0008_),
    .GATE_N(_0068_),
    .Q(\DDATA[9][2] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0989_ (
    .D(_0009_),
    .GATE_N(_0068_),
    .Q(\DDATA[9][3] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0990_ (
    .D(_0010_),
    .GATE_N(_0068_),
    .Q(\DDATA[9][4] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0991_ (
    .D(_0011_),
    .GATE_N(_0068_),
    .Q(\DDATA[9][5] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0992_ (
    .D(_0012_),
    .GATE_N(_0068_),
    .Q(\DDATA[9][6] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0993_ (
    .D(_0013_),
    .GATE_N(_0068_),
    .Q(\DDATA[9][7] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0994_ (
    .D(_0014_),
    .GATE_N(_0068_),
    .Q(\DDATA[9][8] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0995_ (
    .D(_0015_),
    .GATE_N(_0068_),
    .Q(\DDATA[9][9] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0996_ (
    .D(_0001_),
    .GATE_N(_0068_),
    .Q(\DDATA[9][10] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0997_ (
    .D(_0002_),
    .GATE_N(_0068_),
    .Q(\DDATA[9][11] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0998_ (
    .D(_0003_),
    .GATE_N(_0068_),
    .Q(\DDATA[9][12] )
  );
  sky130_fd_sc_hd__dlxtn_1 _0999_ (
    .D(_0004_),
    .GATE_N(_0068_),
    .Q(\DDATA[9][13] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1000_ (
    .D(_0005_),
    .GATE_N(_0068_),
    .Q(\DDATA[9][14] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1001_ (
    .D(_0006_),
    .GATE_N(_0068_),
    .Q(\DDATA[9][15] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1002_ (
    .D(_0000_),
    .GATE_N(_0069_),
    .Q(\DDATA[10][0] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1003_ (
    .D(_0007_),
    .GATE_N(_0069_),
    .Q(\DDATA[10][1] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1004_ (
    .D(_0008_),
    .GATE_N(_0069_),
    .Q(\DDATA[10][2] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1005_ (
    .D(_0009_),
    .GATE_N(_0069_),
    .Q(\DDATA[10][3] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1006_ (
    .D(_0010_),
    .GATE_N(_0069_),
    .Q(\DDATA[10][4] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1007_ (
    .D(_0011_),
    .GATE_N(_0069_),
    .Q(\DDATA[10][5] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1008_ (
    .D(_0012_),
    .GATE_N(_0069_),
    .Q(\DDATA[10][6] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1009_ (
    .D(_0013_),
    .GATE_N(_0069_),
    .Q(\DDATA[10][7] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1010_ (
    .D(_0014_),
    .GATE_N(_0069_),
    .Q(\DDATA[10][8] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1011_ (
    .D(_0015_),
    .GATE_N(_0069_),
    .Q(\DDATA[10][9] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1012_ (
    .D(_0001_),
    .GATE_N(_0069_),
    .Q(\DDATA[10][10] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1013_ (
    .D(_0002_),
    .GATE_N(_0069_),
    .Q(\DDATA[10][11] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1014_ (
    .D(_0003_),
    .GATE_N(_0069_),
    .Q(\DDATA[10][12] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1015_ (
    .D(_0004_),
    .GATE_N(_0069_),
    .Q(\DDATA[10][13] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1016_ (
    .D(_0005_),
    .GATE_N(_0069_),
    .Q(\DDATA[10][14] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1017_ (
    .D(_0006_),
    .GATE_N(_0069_),
    .Q(\DDATA[10][15] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1018_ (
    .D(_0000_),
    .GATE_N(_0070_),
    .Q(\DDATA[11][0] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1019_ (
    .D(_0007_),
    .GATE_N(_0070_),
    .Q(\DDATA[11][1] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1020_ (
    .D(_0008_),
    .GATE_N(_0070_),
    .Q(\DDATA[11][2] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1021_ (
    .D(_0009_),
    .GATE_N(_0070_),
    .Q(\DDATA[11][3] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1022_ (
    .D(_0010_),
    .GATE_N(_0070_),
    .Q(\DDATA[11][4] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1023_ (
    .D(_0011_),
    .GATE_N(_0070_),
    .Q(\DDATA[11][5] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1024_ (
    .D(_0012_),
    .GATE_N(_0070_),
    .Q(\DDATA[11][6] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1025_ (
    .D(_0013_),
    .GATE_N(_0070_),
    .Q(\DDATA[11][7] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1026_ (
    .D(_0014_),
    .GATE_N(_0070_),
    .Q(\DDATA[11][8] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1027_ (
    .D(_0015_),
    .GATE_N(_0070_),
    .Q(\DDATA[11][9] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1028_ (
    .D(_0001_),
    .GATE_N(_0070_),
    .Q(\DDATA[11][10] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1029_ (
    .D(_0002_),
    .GATE_N(_0070_),
    .Q(\DDATA[11][11] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1030_ (
    .D(_0003_),
    .GATE_N(_0070_),
    .Q(\DDATA[11][12] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1031_ (
    .D(_0004_),
    .GATE_N(_0070_),
    .Q(\DDATA[11][13] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1032_ (
    .D(_0005_),
    .GATE_N(_0070_),
    .Q(\DDATA[11][14] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1033_ (
    .D(_0006_),
    .GATE_N(_0070_),
    .Q(\DDATA[11][15] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1034_ (
    .D(_0000_),
    .GATE_N(_0071_),
    .Q(\DDATA[12][0] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1035_ (
    .D(_0007_),
    .GATE_N(_0071_),
    .Q(\DDATA[12][1] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1036_ (
    .D(_0008_),
    .GATE_N(_0071_),
    .Q(\DDATA[12][2] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1037_ (
    .D(_0009_),
    .GATE_N(_0071_),
    .Q(\DDATA[12][3] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1038_ (
    .D(_0010_),
    .GATE_N(_0071_),
    .Q(\DDATA[12][4] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1039_ (
    .D(_0011_),
    .GATE_N(_0071_),
    .Q(\DDATA[12][5] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1040_ (
    .D(_0012_),
    .GATE_N(_0071_),
    .Q(\DDATA[12][6] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1041_ (
    .D(_0013_),
    .GATE_N(_0071_),
    .Q(\DDATA[12][7] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1042_ (
    .D(_0014_),
    .GATE_N(_0071_),
    .Q(\DDATA[12][8] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1043_ (
    .D(_0015_),
    .GATE_N(_0071_),
    .Q(\DDATA[12][9] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1044_ (
    .D(_0001_),
    .GATE_N(_0071_),
    .Q(\DDATA[12][10] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1045_ (
    .D(_0002_),
    .GATE_N(_0071_),
    .Q(\DDATA[12][11] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1046_ (
    .D(_0003_),
    .GATE_N(_0071_),
    .Q(\DDATA[12][12] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1047_ (
    .D(_0004_),
    .GATE_N(_0071_),
    .Q(\DDATA[12][13] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1048_ (
    .D(_0005_),
    .GATE_N(_0071_),
    .Q(\DDATA[12][14] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1049_ (
    .D(_0006_),
    .GATE_N(_0071_),
    .Q(\DDATA[12][15] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1050_ (
    .D(_0000_),
    .GATE_N(_0072_),
    .Q(\DDATA[13][0] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1051_ (
    .D(_0007_),
    .GATE_N(_0072_),
    .Q(\DDATA[13][1] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1052_ (
    .D(_0008_),
    .GATE_N(_0072_),
    .Q(\DDATA[13][2] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1053_ (
    .D(_0009_),
    .GATE_N(_0072_),
    .Q(\DDATA[13][3] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1054_ (
    .D(_0010_),
    .GATE_N(_0072_),
    .Q(\DDATA[13][4] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1055_ (
    .D(_0011_),
    .GATE_N(_0072_),
    .Q(\DDATA[13][5] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1056_ (
    .D(_0012_),
    .GATE_N(_0072_),
    .Q(\DDATA[13][6] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1057_ (
    .D(_0013_),
    .GATE_N(_0072_),
    .Q(\DDATA[13][7] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1058_ (
    .D(_0014_),
    .GATE_N(_0072_),
    .Q(\DDATA[13][8] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1059_ (
    .D(_0015_),
    .GATE_N(_0072_),
    .Q(\DDATA[13][9] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1060_ (
    .D(_0001_),
    .GATE_N(_0072_),
    .Q(\DDATA[13][10] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1061_ (
    .D(_0002_),
    .GATE_N(_0072_),
    .Q(\DDATA[13][11] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1062_ (
    .D(_0003_),
    .GATE_N(_0072_),
    .Q(\DDATA[13][12] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1063_ (
    .D(_0004_),
    .GATE_N(_0072_),
    .Q(\DDATA[13][13] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1064_ (
    .D(_0005_),
    .GATE_N(_0072_),
    .Q(\DDATA[13][14] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1065_ (
    .D(_0006_),
    .GATE_N(_0072_),
    .Q(\DDATA[13][15] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1066_ (
    .D(_0000_),
    .GATE_N(_0073_),
    .Q(\DDATA[14][0] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1067_ (
    .D(_0007_),
    .GATE_N(_0073_),
    .Q(\DDATA[14][1] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1068_ (
    .D(_0008_),
    .GATE_N(_0073_),
    .Q(\DDATA[14][2] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1069_ (
    .D(_0009_),
    .GATE_N(_0073_),
    .Q(\DDATA[14][3] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1070_ (
    .D(_0010_),
    .GATE_N(_0073_),
    .Q(\DDATA[14][4] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1071_ (
    .D(_0011_),
    .GATE_N(_0073_),
    .Q(\DDATA[14][5] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1072_ (
    .D(_0012_),
    .GATE_N(_0073_),
    .Q(\DDATA[14][6] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1073_ (
    .D(_0013_),
    .GATE_N(_0073_),
    .Q(\DDATA[14][7] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1074_ (
    .D(_0014_),
    .GATE_N(_0073_),
    .Q(\DDATA[14][8] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1075_ (
    .D(_0015_),
    .GATE_N(_0073_),
    .Q(\DDATA[14][9] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1076_ (
    .D(_0001_),
    .GATE_N(_0073_),
    .Q(\DDATA[14][10] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1077_ (
    .D(_0002_),
    .GATE_N(_0073_),
    .Q(\DDATA[14][11] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1078_ (
    .D(_0003_),
    .GATE_N(_0073_),
    .Q(\DDATA[14][12] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1079_ (
    .D(_0004_),
    .GATE_N(_0073_),
    .Q(\DDATA[14][13] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1080_ (
    .D(_0005_),
    .GATE_N(_0073_),
    .Q(\DDATA[14][14] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1081_ (
    .D(_0006_),
    .GATE_N(_0073_),
    .Q(\DDATA[14][15] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1082_ (
    .D(_0000_),
    .GATE_N(_0074_),
    .Q(\DDATA[15][0] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1083_ (
    .D(_0007_),
    .GATE_N(_0074_),
    .Q(\DDATA[15][1] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1084_ (
    .D(_0008_),
    .GATE_N(_0074_),
    .Q(\DDATA[15][2] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1085_ (
    .D(_0009_),
    .GATE_N(_0074_),
    .Q(\DDATA[15][3] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1086_ (
    .D(_0010_),
    .GATE_N(_0074_),
    .Q(\DDATA[15][4] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1087_ (
    .D(_0011_),
    .GATE_N(_0074_),
    .Q(\DDATA[15][5] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1088_ (
    .D(_0012_),
    .GATE_N(_0074_),
    .Q(\DDATA[15][6] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1089_ (
    .D(_0013_),
    .GATE_N(_0074_),
    .Q(\DDATA[15][7] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1090_ (
    .D(_0014_),
    .GATE_N(_0074_),
    .Q(\DDATA[15][8] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1091_ (
    .D(_0015_),
    .GATE_N(_0074_),
    .Q(\DDATA[15][9] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1092_ (
    .D(_0001_),
    .GATE_N(_0074_),
    .Q(\DDATA[15][10] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1093_ (
    .D(_0002_),
    .GATE_N(_0074_),
    .Q(\DDATA[15][11] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1094_ (
    .D(_0003_),
    .GATE_N(_0074_),
    .Q(\DDATA[15][12] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1095_ (
    .D(_0004_),
    .GATE_N(_0074_),
    .Q(\DDATA[15][13] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1096_ (
    .D(_0005_),
    .GATE_N(_0074_),
    .Q(\DDATA[15][14] )
  );
  sky130_fd_sc_hd__dlxtn_1 _1097_ (
    .D(_0006_),
    .GATE_N(_0074_),
    .Q(\DDATA[15][15] )
  );
  sky130_fd_sc_hd__dfrtp_2 _1098_ (
    .CLK(clk),
    .D(_0083_),
    .Q(\lenM[0] ),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1099_ (
    .CLK(clk),
    .D(_0084_),
    .Q(\lenM[1] ),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1100_ (
    .CLK(clk),
    .D(_0085_),
    .Q(\lenM[2] ),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1101_ (
    .CLK(clk),
    .D(_0086_),
    .Q(\lenM[3] ),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1102_ (
    .CLK(clk),
    .D(_0087_),
    .Q(\DADDR[0] ),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1103_ (
    .CLK(clk),
    .D(_0088_),
    .Q(\DADDR[1] ),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1104_ (
    .CLK(clk),
    .D(_0089_),
    .Q(\DADDR[2] ),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1105_ (
    .CLK(clk),
    .D(_0090_),
    .Q(\i[0] ),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1106_ (
    .CLK(clk),
    .D(_0091_),
    .Q(\i[1] ),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1107_ (
    .CLK(clk),
    .D(_0092_),
    .Q(\i[2] ),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1108_ (
    .CLK(clk),
    .D(_0093_),
    .Q(\i[3] ),
    .RESET_B(res_n)
  );
  sky130_fd_sc_hd__buf_2 _1109_ (
    .A(bresp),
    .X(bvalid)
  );
  sky130_fd_sc_hd__buf_2 _1110_ (
    .A(rresp),
    .X(rvalid)
  );
endmodule
